#include <assert.h>
#include "demux_test.h"

/* C code generated by lustrec
   SVN version number 1.1-Unversioned directory
   Code is C99 compliant */
   
/* Import dependencies */

/* Global constants (definitions) */

/* Struct definitions */
struct demux_test_mem {struct _arrow_mem *ni_0; };


void demux_test_reset (struct demux_test_mem *self) {
  
  _arrow_reset(self->ni_0);
  return;
}

void demux_test_step (double In1_1_1, double In1_1_2, double In2_1_1,
                      double In2_1_2, double In2_1_3, 
                      double (*Out1_1_1), double (*Out2_2_1),
                      double (*Out3_3_1), double (*Out4_4_1),
                      double (*Out4_4_2),
                      struct demux_test_mem *self) {
  _Bool __demux_test_1;
  double i_virtual_local;
  
  _arrow_step (1, 0, &__demux_test_1, self->ni_0);
  if (__demux_test_1) {
    i_virtual_local = 0.;
  } else {
    i_virtual_local = 1.;
  }
  *Out4_4_2 = In2_1_3;
  *Out4_4_1 = In2_1_2;
  *Out3_3_1 = In2_1_1;
  *Out2_2_1 = In1_1_2;
  *Out1_1_1 = In1_1_1;
  return;
}

