#include <stdio.h>
#include <unistd.h>
#include "/usr/local/include/lustrec/io_frontend.h"
#include <stdlib.h>
#include <assert.h>
#include "demux_test_alloc.h"

/* C code generated by lustrec
   SVN version number 1.1-Unversioned directory
   Code is C99 compliant */
   
int main (int argc, char *argv[]) {
  /* Declaration of inputs/outputs variables */
  double In1_1_1 = 0.;
  double In1_1_2 = 0.;
  double In2_1_1 = 0.;
  double In2_1_2 = 0.;
  double In2_1_3 = 0.;
  double Out1_1_1 = 0.;
  double Out2_2_1 = 0.;
  double Out3_3_1 = 0.;
  double Out4_4_1 = 0.;
  double Out4_4_2 = 0.;
  
  /* Main memory allocation */
  demux_test_ALLOC(static,main_mem);
  
  /* Initialize the main memory */
  demux_test_reset(&main_mem);
  
  ISATTY = isatty(0);
  
  /* Infinite loop */
  while(1){
    fflush(stdout);
    In1_1_1 = _get_double("In1_1_1");
    In1_1_2 = _get_double("In1_1_2");
    In2_1_1 = _get_double("In2_1_1");
    In2_1_2 = _get_double("In2_1_2");
    In2_1_3 = _get_double("In2_1_3");
    demux_test_step(In1_1_1, In1_1_2, In2_1_1, In2_1_2, In2_1_3, &Out1_1_1, &Out2_2_1, &Out3_3_1, &Out4_4_1, &Out4_4_2, &main_mem);
    _put_double("Out1_1_1", Out1_1_1);
    _put_double("Out2_2_1", Out2_2_1);
    _put_double("Out3_3_1", Out3_3_1);
    _put_double("Out4_4_1", Out4_4_1);
    _put_double("Out4_4_2", Out4_4_2);
  }
  return 1;
}
