/* C code generated by lustrec
   SVN version number 1.1-Unversioned directory
   Code is C99 compliant */
   
#ifndef _DEMUX_TEST
#define _DEMUX_TEST

/* Imports standard library */
#include "/usr/local/include/lustrec/arrow.h"


/* Import dependencies */

/* Types definitions */

/* Global constant (declarations, definitions are in C file) */

/* Struct declarations */
struct demux_test_mem;

/* Nodes declarations */
extern void demux_test_reset (struct demux_test_mem *self);

extern void demux_test_step (double In1_1_1, double In1_1_2, double In2_1_1,
                             double In2_1_2, double In2_1_3, 
                             double (*Out1_1_1), double (*Out2_2_1),
                             double (*Out3_3_1), double (*Out4_4_1),
                             double (*Out4_4_2),
                             struct demux_test_mem *self);


#endif

