#include <stdio.h>
#include <unistd.h>
#include "/usr/local/include/lustrec/io_frontend.h"
#include <stdlib.h>
#include <assert.h>
#include "gain_test_Kuuvect_alloc.h"

/* C code generated by lustrec
   SVN version number 1.1-Unversioned directory
   Code is C99 compliant */
   
int main (int argc, char *argv[]) {
  /* Declaration of inputs/outputs variables */
  double In1_1_1 = 0.;
  int In2_1_1 = 0;
  _Bool In3_1_1 = 0;
  double In4_1_1 = 0.;
  double In4_1_2 = 0.;
  int In5_1_1 = 0;
  int In5_1_2 = 0;
  _Bool In6_1_1 = 0;
  _Bool In6_1_2 = 0;
  double In7_1_1 = 0.;
  double In7_1_2 = 0.;
  int In8_1_1 = 0;
  int In8_1_2 = 0;
  _Bool In9_1_1 = 0;
  _Bool In9_1_2 = 0;
  double Out1_1_1 = 0.;
  double Out2_2_1 = 0.;
  double Out3_3_1 = 0.;
  double Out4_4_1 = 0.;
  double Out5_5_1 = 0.;
  double Out6_6_1 = 0.;
  double Out7_7_1 = 0.;
  double Out7_7_2 = 0.;
  double Out8_8_1 = 0.;
  double Out8_8_2 = 0.;
  double Out9_9_1 = 0.;
  double Out9_9_2 = 0.;
  
  /* Main memory allocation */
  gain_test_Kuuvect_ALLOC(static,main_mem);
  
  /* Initialize the main memory */
  gain_test_Kuuvect_reset(&main_mem);
  
  ISATTY = isatty(0);
  
  /* Infinite loop */
  while(1){
    fflush(stdout);
    In1_1_1 = _get_double("In1_1_1");
    In2_1_1 = _get_int("In2_1_1");
    In3_1_1 = _get_bool("In3_1_1");
    In4_1_1 = _get_double("In4_1_1");
    In4_1_2 = _get_double("In4_1_2");
    In5_1_1 = _get_int("In5_1_1");
    In5_1_2 = _get_int("In5_1_2");
    In6_1_1 = _get_bool("In6_1_1");
    In6_1_2 = _get_bool("In6_1_2");
    In7_1_1 = _get_double("In7_1_1");
    In7_1_2 = _get_double("In7_1_2");
    In8_1_1 = _get_int("In8_1_1");
    In8_1_2 = _get_int("In8_1_2");
    In9_1_1 = _get_bool("In9_1_1");
    In9_1_2 = _get_bool("In9_1_2");
    gain_test_Kuuvect_step(In1_1_1, In2_1_1, In3_1_1, In4_1_1, In4_1_2, In5_1_1, In5_1_2, In6_1_1, In6_1_2, In7_1_1, In7_1_2, In8_1_1, In8_1_2, In9_1_1, In9_1_2, &Out1_1_1, &Out2_2_1, &Out3_3_1, &Out4_4_1, &Out5_5_1, &Out6_6_1, &Out7_7_1, &Out7_7_2, &Out8_8_1, &Out8_8_2, &Out9_9_1, &Out9_9_2, &main_mem);
    _put_double("Out1_1_1", Out1_1_1);
    _put_double("Out2_2_1", Out2_2_1);
    _put_double("Out3_3_1", Out3_3_1);
    _put_double("Out4_4_1", Out4_4_1);
    _put_double("Out5_5_1", Out5_5_1);
    _put_double("Out6_6_1", Out6_6_1);
    _put_double("Out7_7_1", Out7_7_1);
    _put_double("Out7_7_2", Out7_7_2);
    _put_double("Out8_8_1", Out8_8_1);
    _put_double("Out8_8_2", Out8_8_2);
    _put_double("Out9_9_1", Out9_9_1);
    _put_double("Out9_9_2", Out9_9_2);
  }
  return 1;
}
