/* C code generated by lustrec
   SVN version number 1.1-Unversioned directory
   Code is C99 compliant */
   
#ifndef _GAIN_TEST_KUUVECT_alloc
#define _GAIN_TEST_KUUVECT_alloc

/* Import header from gain_test_Kuuvect */
#include "gain_test_Kuuvect.h"

/* Import dependencies */

/* Struct definitions */
struct gain_test_Kuuvect_mem {struct _arrow_mem *ni_0; };

/* Node allocation function/macro prototypes */
#define gain_test_Kuuvect_DECLARE(attr, inst)\
  attr struct gain_test_Kuuvect_mem inst;\
  _arrow_DECLARE(attr, inst ## _ni_0);
  
#define gain_test_Kuuvect_LINK(inst) do {\
  _arrow_LINK(inst ## _ni_0);\
  inst.ni_0 = &inst ## _ni_0;\
} while (0)

#define gain_test_Kuuvect_ALLOC(attr, inst)\
  gain_test_Kuuvect_DECLARE(attr, inst);\
  gain_test_Kuuvect_LINK(inst);



#endif

