/* C code generated by lustrec
   SVN version number 1.1-Unversioned directory
   Code is C99 compliant */
   
#ifndef _GAIN_TEST_KUUVECT
#define _GAIN_TEST_KUUVECT

/* Imports standard library */
#include "/usr/local/include/lustrec/arrow.h"


/* Import dependencies */
#include "conv.h"

/* Types definitions */

/* Global constant (declarations, definitions are in C file) */

/* Struct declarations */
struct gain_test_Kuuvect_mem;

/* Nodes declarations */
extern void gain_test_Kuuvect_reset (struct gain_test_Kuuvect_mem *self);

extern void gain_test_Kuuvect_step (double In1_1_1, int In2_1_1,
                                    _Bool In3_1_1, double In4_1_1,
                                    double In4_1_2, int In5_1_1, int In5_1_2,
                                    _Bool In6_1_1, _Bool In6_1_2,
                                    double In7_1_1, double In7_1_2,
                                    int In8_1_1, int In8_1_2, _Bool In9_1_1,
                                    _Bool In9_1_2, 
                                    double (*Out1_1_1), double (*Out2_2_1),
                                    double (*Out3_3_1), double (*Out4_4_1),
                                    double (*Out5_5_1), double (*Out6_6_1),
                                    double (*Out7_7_1), double (*Out7_7_2),
                                    double (*Out8_8_1), double (*Out8_8_2),
                                    double (*Out9_9_1), double (*Out9_9_2),
                                    struct gain_test_Kuuvect_mem *self);


#endif

