#include <assert.h>
#include "gain_test_Kuuvect.h"

/* C code generated by lustrec
   SVN version number 1.1-Unversioned directory
   Code is C99 compliant */
   
/* Import dependencies */
#include "conv.h"

/* Global constants (definitions) */

/* Struct definitions */
struct gain_test_Kuuvect_mem {struct _arrow_mem *ni_0; };


void gain_test_Kuuvect_reset (struct gain_test_Kuuvect_mem *self) {
  
  _arrow_reset(self->ni_0);
  return;
}

void gain_test_Kuuvect_step (double In1_1_1, int In2_1_1, _Bool In3_1_1,
                             double In4_1_1, double In4_1_2, int In5_1_1,
                             int In5_1_2, _Bool In6_1_1, _Bool In6_1_2,
                             double In7_1_1, double In7_1_2, int In8_1_1,
                             int In8_1_2, _Bool In9_1_1, _Bool In9_1_2, 
                             double (*Out1_1_1), double (*Out2_2_1),
                             double (*Out3_3_1), double (*Out4_4_1),
                             double (*Out5_5_1), double (*Out6_6_1),
                             double (*Out7_7_1), double (*Out7_7_2),
                             double (*Out8_8_1), double (*Out8_8_2),
                             double (*Out9_9_1), double (*Out9_9_2),
                             struct gain_test_Kuuvect_mem *self) {
  _Bool __gain_test_Kuuvect_1;
  double __gain_test_Kuuvect_10;
  double __gain_test_Kuuvect_11;
  double __gain_test_Kuuvect_2;
  double __gain_test_Kuuvect_3;
  double __gain_test_Kuuvect_4;
  double __gain_test_Kuuvect_5;
  double __gain_test_Kuuvect_6;
  double __gain_test_Kuuvect_7;
  double __gain_test_Kuuvect_8;
  double __gain_test_Kuuvect_9;
  double i_virtual_local;
  
  _arrow_step (1, 0, &__gain_test_Kuuvect_1, self->ni_0);
  if (__gain_test_Kuuvect_1) {
    i_virtual_local = 0.;
  } else {
    i_virtual_local = 1.;
  }
  __gain_test_Kuuvect_9 = int_to_real(In5_1_1);
  __gain_test_Kuuvect_8 = int_to_real(In5_1_2);
  if (In6_1_1) {
    __gain_test_Kuuvect_7 = 1.;
  } else {
    __gain_test_Kuuvect_7 = 0.;
  }
  if (In6_1_2) {
    __gain_test_Kuuvect_6 = 1.;
  } else {
    __gain_test_Kuuvect_6 = 0.;
  }
  __gain_test_Kuuvect_5 = int_to_real(In8_1_1);
  __gain_test_Kuuvect_4 = int_to_real(In8_1_2);
  if (In9_1_1) {
    __gain_test_Kuuvect_3 = 1.;
  } else {
    __gain_test_Kuuvect_3 = 0.;
  }
  if (In9_1_2) {
    __gain_test_Kuuvect_2 = 1.;
  } else {
    __gain_test_Kuuvect_2 = 0.;
  }
  __gain_test_Kuuvect_11 = int_to_real(In2_1_1);
  if (In3_1_1) {
    __gain_test_Kuuvect_10 = 1.;
  } else {
    __gain_test_Kuuvect_10 = 0.;
  }
  *Out9_9_2 = ((6. * __gain_test_Kuuvect_3) + (8. * __gain_test_Kuuvect_2));
  *Out9_9_1 = ((2. * __gain_test_Kuuvect_3) + (5. * __gain_test_Kuuvect_2));
  *Out8_8_2 = ((6. * __gain_test_Kuuvect_5) + (8. * __gain_test_Kuuvect_4));
  *Out8_8_1 = ((2. * __gain_test_Kuuvect_5) + (5. * __gain_test_Kuuvect_4));
  *Out7_7_2 = ((6. * In7_1_1) + (8. * In7_1_2));
  *Out7_7_1 = ((2. * In7_1_1) + (5. * In7_1_2));
  *Out6_6_1 = ((2. * __gain_test_Kuuvect_7) + (5. * __gain_test_Kuuvect_6));
  *Out5_5_1 = ((2. * __gain_test_Kuuvect_9) + (5. * __gain_test_Kuuvect_8));
  *Out4_4_1 = ((2. * In4_1_1) + (5. * In4_1_2));
  *Out3_3_1 = (1. * __gain_test_Kuuvect_10);
  *Out2_2_1 = (1. * __gain_test_Kuuvect_11);
  *Out1_1_1 = (1. * In1_1_1);
  return;
}

