#include <stdio.h>
#include <unistd.h>
#include "/usr/local/include/lustrec/io_frontend.h"
#include <stdlib.h>
#include <assert.h>
#include "sum_collapse_bool_test_alloc.h"

/* C code generated by lustrec
   SVN version number 1.1-Unversioned directory
   Code is C99 compliant */
   
int main (int argc, char *argv[]) {
  /* Declaration of inputs/outputs variables */
  _Bool In17_1_1 = 0;
  _Bool In18_1_1 = 0;
  _Bool In19_1_1 = 0;
  _Bool In19_1_2 = 0;
  _Bool In19_1_3 = 0;
  _Bool In20_1_1 = 0;
  _Bool In20_1_2 = 0;
  _Bool In20_1_3 = 0;
  _Bool In21_1_1 = 0;
  _Bool In21_1_2 = 0;
  _Bool In21_1_3 = 0;
  _Bool In21_1_4 = 0;
  _Bool In21_1_5 = 0;
  _Bool In21_1_6 = 0;
  _Bool In22_1_1 = 0;
  _Bool In22_1_2 = 0;
  _Bool In22_1_3 = 0;
  _Bool In22_1_4 = 0;
  _Bool In22_1_5 = 0;
  _Bool In22_1_6 = 0;
  _Bool In23_1_1 = 0;
  _Bool In23_1_2 = 0;
  _Bool In23_1_3 = 0;
  _Bool In23_1_4 = 0;
  _Bool In23_1_5 = 0;
  _Bool In23_1_6 = 0;
  _Bool In24_1_1 = 0;
  _Bool In24_1_2 = 0;
  _Bool In24_1_3 = 0;
  _Bool In24_1_4 = 0;
  _Bool In24_1_5 = 0;
  _Bool In24_1_6 = 0;
  int Out17_1_1 = 0;
  int Out18_2_1 = 0;
  int Out19_3_1 = 0;
  int Out20_4_1 = 0;
  int Out21_5_1 = 0;
  int Out21_5_2 = 0;
  int Out21_5_3 = 0;
  int Out22_6_1 = 0;
  int Out22_6_2 = 0;
  int Out22_6_3 = 0;
  int Out23_7_1 = 0;
  int Out23_7_2 = 0;
  int Out24_8_1 = 0;
  int Out24_8_2 = 0;
  
  /* Main memory allocation */
  sum_collapse_bool_test_ALLOC(static,main_mem);
  
  /* Initialize the main memory */
  sum_collapse_bool_test_reset(&main_mem);
  
  ISATTY = isatty(0);
  
  /* Infinite loop */
  while(1){
    fflush(stdout);
    In17_1_1 = _get_bool("In17_1_1");
    In18_1_1 = _get_bool("In18_1_1");
    In19_1_1 = _get_bool("In19_1_1");
    In19_1_2 = _get_bool("In19_1_2");
    In19_1_3 = _get_bool("In19_1_3");
    In20_1_1 = _get_bool("In20_1_1");
    In20_1_2 = _get_bool("In20_1_2");
    In20_1_3 = _get_bool("In20_1_3");
    In21_1_1 = _get_bool("In21_1_1");
    In21_1_2 = _get_bool("In21_1_2");
    In21_1_3 = _get_bool("In21_1_3");
    In21_1_4 = _get_bool("In21_1_4");
    In21_1_5 = _get_bool("In21_1_5");
    In21_1_6 = _get_bool("In21_1_6");
    In22_1_1 = _get_bool("In22_1_1");
    In22_1_2 = _get_bool("In22_1_2");
    In22_1_3 = _get_bool("In22_1_3");
    In22_1_4 = _get_bool("In22_1_4");
    In22_1_5 = _get_bool("In22_1_5");
    In22_1_6 = _get_bool("In22_1_6");
    In23_1_1 = _get_bool("In23_1_1");
    In23_1_2 = _get_bool("In23_1_2");
    In23_1_3 = _get_bool("In23_1_3");
    In23_1_4 = _get_bool("In23_1_4");
    In23_1_5 = _get_bool("In23_1_5");
    In23_1_6 = _get_bool("In23_1_6");
    In24_1_1 = _get_bool("In24_1_1");
    In24_1_2 = _get_bool("In24_1_2");
    In24_1_3 = _get_bool("In24_1_3");
    In24_1_4 = _get_bool("In24_1_4");
    In24_1_5 = _get_bool("In24_1_5");
    In24_1_6 = _get_bool("In24_1_6");
    sum_collapse_bool_test_step(In17_1_1, In18_1_1, In19_1_1, In19_1_2, In19_1_3, In20_1_1, In20_1_2, In20_1_3, In21_1_1, In21_1_2, In21_1_3, In21_1_4, In21_1_5, In21_1_6, In22_1_1, In22_1_2, In22_1_3, In22_1_4, In22_1_5, In22_1_6, In23_1_1, In23_1_2, In23_1_3, In23_1_4, In23_1_5, In23_1_6, In24_1_1, In24_1_2, In24_1_3, In24_1_4, In24_1_5, In24_1_6, &Out17_1_1, &Out18_2_1, &Out19_3_1, &Out20_4_1, &Out21_5_1, &Out21_5_2, &Out21_5_3, &Out22_6_1, &Out22_6_2, &Out22_6_3, &Out23_7_1, &Out23_7_2, &Out24_8_1, &Out24_8_2, &main_mem);
    _put_int("Out17_1_1", Out17_1_1);
    _put_int("Out18_2_1", Out18_2_1);
    _put_int("Out19_3_1", Out19_3_1);
    _put_int("Out20_4_1", Out20_4_1);
    _put_int("Out21_5_1", Out21_5_1);
    _put_int("Out21_5_2", Out21_5_2);
    _put_int("Out21_5_3", Out21_5_3);
    _put_int("Out22_6_1", Out22_6_1);
    _put_int("Out22_6_2", Out22_6_2);
    _put_int("Out22_6_3", Out22_6_3);
    _put_int("Out23_7_1", Out23_7_1);
    _put_int("Out23_7_2", Out23_7_2);
    _put_int("Out24_8_1", Out24_8_1);
    _put_int("Out24_8_2", Out24_8_2);
  }
  return 1;
}
