#include <assert.h>
#include "sum_collapse_bool_test.h"

/* C code generated by lustrec
   SVN version number 1.1-Unversioned directory
   Code is C99 compliant */
   
/* Import dependencies */

/* Global constants (definitions) */

/* Struct definitions */
struct sum_collapse_bool_test_mem {struct _arrow_mem *ni_0; };


void sum_collapse_bool_test_reset (struct sum_collapse_bool_test_mem *self) {
  
  _arrow_reset(self->ni_0);
  return;
}

void sum_collapse_bool_test_step (_Bool In17_1_1, _Bool In18_1_1,
                                  _Bool In19_1_1, _Bool In19_1_2,
                                  _Bool In19_1_3, _Bool In20_1_1,
                                  _Bool In20_1_2, _Bool In20_1_3,
                                  _Bool In21_1_1, _Bool In21_1_2,
                                  _Bool In21_1_3, _Bool In21_1_4,
                                  _Bool In21_1_5, _Bool In21_1_6,
                                  _Bool In22_1_1, _Bool In22_1_2,
                                  _Bool In22_1_3, _Bool In22_1_4,
                                  _Bool In22_1_5, _Bool In22_1_6,
                                  _Bool In23_1_1, _Bool In23_1_2,
                                  _Bool In23_1_3, _Bool In23_1_4,
                                  _Bool In23_1_5, _Bool In23_1_6,
                                  _Bool In24_1_1, _Bool In24_1_2,
                                  _Bool In24_1_3, _Bool In24_1_4,
                                  _Bool In24_1_5, _Bool In24_1_6, 
                                  int (*Out17_1_1), int (*Out18_2_1),
                                  int (*Out19_3_1), int (*Out20_4_1),
                                  int (*Out21_5_1), int (*Out21_5_2),
                                  int (*Out21_5_3), int (*Out22_6_1),
                                  int (*Out22_6_2), int (*Out22_6_3),
                                  int (*Out23_7_1), int (*Out23_7_2),
                                  int (*Out24_8_1), int (*Out24_8_2),
                                  struct sum_collapse_bool_test_mem *self) {
  int Sum16_1_1;
  _Bool __sum_collapse_bool_test_1;
  int __sum_collapse_bool_test_10;
  int __sum_collapse_bool_test_11;
  int __sum_collapse_bool_test_12;
  int __sum_collapse_bool_test_13;
  int __sum_collapse_bool_test_14;
  int __sum_collapse_bool_test_15;
  int __sum_collapse_bool_test_16;
  int __sum_collapse_bool_test_17;
  int __sum_collapse_bool_test_18;
  int __sum_collapse_bool_test_19;
  int __sum_collapse_bool_test_2;
  int __sum_collapse_bool_test_20;
  int __sum_collapse_bool_test_21;
  int __sum_collapse_bool_test_22;
  int __sum_collapse_bool_test_23;
  int __sum_collapse_bool_test_24;
  int __sum_collapse_bool_test_25;
  int __sum_collapse_bool_test_26;
  int __sum_collapse_bool_test_27;
  int __sum_collapse_bool_test_28;
  int __sum_collapse_bool_test_29;
  int __sum_collapse_bool_test_3;
  int __sum_collapse_bool_test_30;
  int __sum_collapse_bool_test_31;
  int __sum_collapse_bool_test_32;
  int __sum_collapse_bool_test_4;
  int __sum_collapse_bool_test_5;
  int __sum_collapse_bool_test_6;
  int __sum_collapse_bool_test_7;
  int __sum_collapse_bool_test_8;
  int __sum_collapse_bool_test_9;
  double i_virtual_local;
  
  _arrow_step (1, 0, &__sum_collapse_bool_test_1, self->ni_0);
  if (__sum_collapse_bool_test_1) {
    i_virtual_local = 0.;
  } else {
    i_virtual_local = 1.;
  }
  if (In23_1_5) {
    __sum_collapse_bool_test_9 = 1;
  } else {
    __sum_collapse_bool_test_9 = 0;
  }
  if (In23_1_6) {
    __sum_collapse_bool_test_8 = 1;
  } else {
    __sum_collapse_bool_test_8 = 0;
  }
  if (In24_1_1) {
    __sum_collapse_bool_test_7 = 1;
  } else {
    __sum_collapse_bool_test_7 = 0;
  }
  if (In24_1_2) {
    __sum_collapse_bool_test_6 = 1;
  } else {
    __sum_collapse_bool_test_6 = 0;
  }
  if (In24_1_3) {
    __sum_collapse_bool_test_5 = 1;
  } else {
    __sum_collapse_bool_test_5 = 0;
  }
  if (In24_1_4) {
    __sum_collapse_bool_test_4 = 1;
  } else {
    __sum_collapse_bool_test_4 = 0;
  }
  if (In21_1_1) {
    __sum_collapse_bool_test_32 = 1;
  } else {
    __sum_collapse_bool_test_32 = 0;
  }
  if (In21_1_4) {
    __sum_collapse_bool_test_31 = 1;
  } else {
    __sum_collapse_bool_test_31 = 0;
  }
  if (In21_1_2) {
    __sum_collapse_bool_test_30 = 1;
  } else {
    __sum_collapse_bool_test_30 = 0;
  }
  if (In24_1_5) {
    __sum_collapse_bool_test_3 = 1;
  } else {
    __sum_collapse_bool_test_3 = 0;
  }
  if (In21_1_5) {
    __sum_collapse_bool_test_29 = 1;
  } else {
    __sum_collapse_bool_test_29 = 0;
  }
  if (In21_1_3) {
    __sum_collapse_bool_test_28 = 1;
  } else {
    __sum_collapse_bool_test_28 = 0;
  }
  if (In21_1_6) {
    __sum_collapse_bool_test_27 = 1;
  } else {
    __sum_collapse_bool_test_27 = 0;
  }
  if (In22_1_1) {
    __sum_collapse_bool_test_26 = 1;
  } else {
    __sum_collapse_bool_test_26 = 0;
  }
  if (In22_1_4) {
    __sum_collapse_bool_test_25 = 1;
  } else {
    __sum_collapse_bool_test_25 = 0;
  }
  if (In22_1_2) {
    __sum_collapse_bool_test_24 = 1;
  } else {
    __sum_collapse_bool_test_24 = 0;
  }
  if (In22_1_5) {
    __sum_collapse_bool_test_23 = 1;
  } else {
    __sum_collapse_bool_test_23 = 0;
  }
  if (In22_1_3) {
    __sum_collapse_bool_test_22 = 1;
  } else {
    __sum_collapse_bool_test_22 = 0;
  }
  if (In22_1_6) {
    __sum_collapse_bool_test_21 = 1;
  } else {
    __sum_collapse_bool_test_21 = 0;
  }
  if (In18_1_1) {
    __sum_collapse_bool_test_20 = 1;
  } else {
    __sum_collapse_bool_test_20 = 0;
  }
  if (In24_1_6) {
    __sum_collapse_bool_test_2 = 1;
  } else {
    __sum_collapse_bool_test_2 = 0;
  }
  if (In19_1_1) {
    __sum_collapse_bool_test_19 = 1;
  } else {
    __sum_collapse_bool_test_19 = 0;
  }
  if (In19_1_2) {
    __sum_collapse_bool_test_18 = 1;
  } else {
    __sum_collapse_bool_test_18 = 0;
  }
  if (In19_1_3) {
    __sum_collapse_bool_test_17 = 1;
  } else {
    __sum_collapse_bool_test_17 = 0;
  }
  if (In20_1_1) {
    __sum_collapse_bool_test_16 = 1;
  } else {
    __sum_collapse_bool_test_16 = 0;
  }
  if (In20_1_2) {
    __sum_collapse_bool_test_15 = 1;
  } else {
    __sum_collapse_bool_test_15 = 0;
  }
  if (In20_1_3) {
    __sum_collapse_bool_test_14 = 1;
  } else {
    __sum_collapse_bool_test_14 = 0;
  }
  if (In23_1_1) {
    __sum_collapse_bool_test_13 = 1;
  } else {
    __sum_collapse_bool_test_13 = 0;
  }
  if (In23_1_2) {
    __sum_collapse_bool_test_12 = 1;
  } else {
    __sum_collapse_bool_test_12 = 0;
  }
  if (In23_1_3) {
    __sum_collapse_bool_test_11 = 1;
  } else {
    __sum_collapse_bool_test_11 = 0;
  }
  if (In23_1_4) {
    __sum_collapse_bool_test_10 = 1;
  } else {
    __sum_collapse_bool_test_10 = 0;
  }
  if (In17_1_1) {
    Sum16_1_1 = 1;
  } else {
    Sum16_1_1 = 0;
  }
  *Out24_8_2 = (((- __sum_collapse_bool_test_4) - __sum_collapse_bool_test_3) - __sum_collapse_bool_test_2);
  *Out24_8_1 = (((- __sum_collapse_bool_test_7) - __sum_collapse_bool_test_6) - __sum_collapse_bool_test_5);
  *Out23_7_2 = ((__sum_collapse_bool_test_10 + __sum_collapse_bool_test_9) + __sum_collapse_bool_test_8);
  *Out23_7_1 = ((__sum_collapse_bool_test_13 + __sum_collapse_bool_test_12) + __sum_collapse_bool_test_11);
  *Out22_6_3 = ((- __sum_collapse_bool_test_22) - __sum_collapse_bool_test_21);
  *Out22_6_2 = ((- __sum_collapse_bool_test_24) - __sum_collapse_bool_test_23);
  *Out22_6_1 = ((- __sum_collapse_bool_test_26) - __sum_collapse_bool_test_25);
  *Out21_5_3 = (__sum_collapse_bool_test_28 + __sum_collapse_bool_test_27);
  *Out21_5_2 = (__sum_collapse_bool_test_30 + __sum_collapse_bool_test_29);
  *Out21_5_1 = (__sum_collapse_bool_test_32 + __sum_collapse_bool_test_31);
  *Out20_4_1 = (((- __sum_collapse_bool_test_16) - __sum_collapse_bool_test_15) - __sum_collapse_bool_test_14);
  *Out19_3_1 = ((__sum_collapse_bool_test_19 + __sum_collapse_bool_test_18) + __sum_collapse_bool_test_17);
  *Out18_2_1 = (- __sum_collapse_bool_test_20);
  *Out17_1_1 = Sum16_1_1;
  return;
}

