/* C code generated by lustrec
   SVN version number 1.1-Unversioned directory
   Code is C99 compliant */
   
#ifndef _SUM_COLLAPSE_BOOL_TEST
#define _SUM_COLLAPSE_BOOL_TEST

/* Imports standard library */
#include "/usr/local/include/lustrec/arrow.h"


/* Import dependencies */

/* Types definitions */

/* Global constant (declarations, definitions are in C file) */

/* Struct declarations */
struct sum_collapse_bool_test_mem;

/* Nodes declarations */
extern void sum_collapse_bool_test_reset (struct sum_collapse_bool_test_mem *self);

extern void sum_collapse_bool_test_step (_Bool In17_1_1, _Bool In18_1_1,
                                         _Bool In19_1_1, _Bool In19_1_2,
                                         _Bool In19_1_3, _Bool In20_1_1,
                                         _Bool In20_1_2, _Bool In20_1_3,
                                         _Bool In21_1_1, _Bool In21_1_2,
                                         _Bool In21_1_3, _Bool In21_1_4,
                                         _Bool In21_1_5, _Bool In21_1_6,
                                         _Bool In22_1_1, _Bool In22_1_2,
                                         _Bool In22_1_3, _Bool In22_1_4,
                                         _Bool In22_1_5, _Bool In22_1_6,
                                         _Bool In23_1_1, _Bool In23_1_2,
                                         _Bool In23_1_3, _Bool In23_1_4,
                                         _Bool In23_1_5, _Bool In23_1_6,
                                         _Bool In24_1_1, _Bool In24_1_2,
                                         _Bool In24_1_3, _Bool In24_1_4,
                                         _Bool In24_1_5, _Bool In24_1_6, 
                                         int (*Out17_1_1), int (*Out18_2_1),
                                         int (*Out19_3_1), int (*Out20_4_1),
                                         int (*Out21_5_1), int (*Out21_5_2),
                                         int (*Out21_5_3), int (*Out22_6_1),
                                         int (*Out22_6_2), int (*Out22_6_3),
                                         int (*Out23_7_1), int (*Out23_7_2),
                                         int (*Out24_8_1), int (*Out24_8_2),
                                         struct sum_collapse_bool_test_mem *self);


#endif

