#include <stdio.h>
#include <unistd.h>
#include "/usr/local/include/lustrec/io_frontend.h"
#include <stdlib.h>
#include <assert.h>
#include "assignment_port_test_alloc.h"

/* C code generated by lustrec
   SVN version number 1.1-Unversioned directory
   Code is C99 compliant */
   
int main (int argc, char *argv[]) {
  /* Declaration of inputs/outputs variables */
  double In1_1_1 = 0.;
  double In1_1_2 = 0.;
  double In1_1_3 = 0.;
  double In1_1_4 = 0.;
  double In1_1_5 = 0.;
  double In1_1_6 = 0.;
  _Bool In2_1_1 = 0;
  _Bool In2_1_2 = 0;
  _Bool In2_1_3 = 0;
  _Bool In2_1_4 = 0;
  _Bool In2_1_5 = 0;
  _Bool In2_1_6 = 0;
  int In3_1_1 = 0;
  int In3_1_2 = 0;
  int In3_1_3 = 0;
  int In3_1_4 = 0;
  int In3_1_5 = 0;
  int In3_1_6 = 0;
  double In4_1_1 = 0.;
  double In4_1_2 = 0.;
  double In4_1_3 = 0.;
  _Bool In5_1_1 = 0;
  _Bool In5_1_2 = 0;
  _Bool In5_1_3 = 0;
  int In6_1_1 = 0;
  int In6_1_2 = 0;
  int In6_1_3 = 0;
  int In7_1_1 = 0;
  int In7_1_2 = 0;
  int In7_1_3 = 0;
  int In8_1_1 = 0;
  int In8_1_2 = 0;
  int In8_1_3 = 0;
  int In8_1_4 = 0;
  int In8_1_5 = 0;
  int In8_1_6 = 0;
  double In9_1_1 = 0.;
  double In9_1_2 = 0.;
  int In10_1_1 = 0;
  int In11_1_1 = 0;
  double In12_1_1 = 0.;
  double In12_1_2 = 0.;
  double In13_1_1 = 0.;
  double In13_1_2 = 0.;
  double In13_1_3 = 0.;
  double In14_1_1 = 0.;
  double In14_1_2 = 0.;
  double In15_1_1 = 0.;
  double In16_1_1 = 0.;
  double In17_1_1 = 0.;
  int In18_1_1 = 0;
  int In18_1_2 = 0;
  int In18_1_3 = 0;
  int In18_1_4 = 0;
  int In18_1_5 = 0;
  int In18_1_6 = 0;
  double In19_1_1 = 0.;
  double In19_1_2 = 0.;
  double In20_1_1 = 0.;
  double Out1_1_1 = 0.;
  double Out1_1_2 = 0.;
  double Out1_1_3 = 0.;
  double Out1_1_4 = 0.;
  double Out1_1_5 = 0.;
  double Out1_1_6 = 0.;
  _Bool Out2_2_1 = 0;
  _Bool Out2_2_2 = 0;
  _Bool Out2_2_3 = 0;
  _Bool Out2_2_4 = 0;
  _Bool Out2_2_5 = 0;
  _Bool Out2_2_6 = 0;
  int Out3_3_1 = 0;
  int Out3_3_2 = 0;
  int Out3_3_3 = 0;
  int Out3_3_4 = 0;
  int Out3_3_5 = 0;
  int Out3_3_6 = 0;
  double Out4_4_1 = 0.;
  double Out4_4_2 = 0.;
  double Out4_4_3 = 0.;
  _Bool Out5_5_1 = 0;
  _Bool Out5_5_2 = 0;
  _Bool Out5_5_3 = 0;
  int Out6_6_1 = 0;
  int Out6_6_2 = 0;
  int Out6_6_3 = 0;
  int Out7_7_1 = 0;
  int Out7_7_2 = 0;
  int Out7_7_3 = 0;
  int Out8_8_1 = 0;
  int Out8_8_2 = 0;
  int Out8_8_3 = 0;
  int Out8_8_4 = 0;
  int Out8_8_5 = 0;
  int Out8_8_6 = 0;
  int Out9_9_1 = 0;
  int Out9_9_2 = 0;
  int Out9_9_3 = 0;
  int Out9_9_4 = 0;
  int Out9_9_5 = 0;
  int Out9_9_6 = 0;
  
  /* Main memory allocation */
  assignment_port_test_ALLOC(static,main_mem);
  
  /* Initialize the main memory */
  assignment_port_test_reset(&main_mem);
  
  ISATTY = isatty(0);
  
  /* Infinite loop */
  while(1){
    fflush(stdout);
    In1_1_1 = _get_double("In1_1_1");
    In1_1_2 = _get_double("In1_1_2");
    In1_1_3 = _get_double("In1_1_3");
    In1_1_4 = _get_double("In1_1_4");
    In1_1_5 = _get_double("In1_1_5");
    In1_1_6 = _get_double("In1_1_6");
    In2_1_1 = _get_bool("In2_1_1");
    In2_1_2 = _get_bool("In2_1_2");
    In2_1_3 = _get_bool("In2_1_3");
    In2_1_4 = _get_bool("In2_1_4");
    In2_1_5 = _get_bool("In2_1_5");
    In2_1_6 = _get_bool("In2_1_6");
    In3_1_1 = _get_int("In3_1_1");
    In3_1_2 = _get_int("In3_1_2");
    In3_1_3 = _get_int("In3_1_3");
    In3_1_4 = _get_int("In3_1_4");
    In3_1_5 = _get_int("In3_1_5");
    In3_1_6 = _get_int("In3_1_6");
    In4_1_1 = _get_double("In4_1_1");
    In4_1_2 = _get_double("In4_1_2");
    In4_1_3 = _get_double("In4_1_3");
    In5_1_1 = _get_bool("In5_1_1");
    In5_1_2 = _get_bool("In5_1_2");
    In5_1_3 = _get_bool("In5_1_3");
    In6_1_1 = _get_int("In6_1_1");
    In6_1_2 = _get_int("In6_1_2");
    In6_1_3 = _get_int("In6_1_3");
    In7_1_1 = _get_int("In7_1_1");
    In7_1_2 = _get_int("In7_1_2");
    In7_1_3 = _get_int("In7_1_3");
    In8_1_1 = _get_int("In8_1_1");
    In8_1_2 = _get_int("In8_1_2");
    In8_1_3 = _get_int("In8_1_3");
    In8_1_4 = _get_int("In8_1_4");
    In8_1_5 = _get_int("In8_1_5");
    In8_1_6 = _get_int("In8_1_6");
    In9_1_1 = _get_double("In9_1_1");
    In9_1_2 = _get_double("In9_1_2");
    In10_1_1 = _get_int("In10_1_1");
    In11_1_1 = _get_int("In11_1_1");
    In12_1_1 = _get_double("In12_1_1");
    In12_1_2 = _get_double("In12_1_2");
    In13_1_1 = _get_double("In13_1_1");
    In13_1_2 = _get_double("In13_1_2");
    In13_1_3 = _get_double("In13_1_3");
    In14_1_1 = _get_double("In14_1_1");
    In14_1_2 = _get_double("In14_1_2");
    In15_1_1 = _get_double("In15_1_1");
    In16_1_1 = _get_double("In16_1_1");
    In17_1_1 = _get_double("In17_1_1");
    In18_1_1 = _get_int("In18_1_1");
    In18_1_2 = _get_int("In18_1_2");
    In18_1_3 = _get_int("In18_1_3");
    In18_1_4 = _get_int("In18_1_4");
    In18_1_5 = _get_int("In18_1_5");
    In18_1_6 = _get_int("In18_1_6");
    In19_1_1 = _get_double("In19_1_1");
    In19_1_2 = _get_double("In19_1_2");
    In20_1_1 = _get_double("In20_1_1");
    assignment_port_test_step(In1_1_1, In1_1_2, In1_1_3, In1_1_4, In1_1_5, In1_1_6, In2_1_1, In2_1_2, In2_1_3, In2_1_4, In2_1_5, In2_1_6, In3_1_1, In3_1_2, In3_1_3, In3_1_4, In3_1_5, In3_1_6, In4_1_1, In4_1_2, In4_1_3, In5_1_1, In5_1_2, In5_1_3, In6_1_1, In6_1_2, In6_1_3, In7_1_1, In7_1_2, In7_1_3, In8_1_1, In8_1_2, In8_1_3, In8_1_4, In8_1_5, In8_1_6, In9_1_1, In9_1_2, In10_1_1, In11_1_1, In12_1_1, In12_1_2, In13_1_1, In13_1_2, In13_1_3, In14_1_1, In14_1_2, In15_1_1, In16_1_1, In17_1_1, In18_1_1, In18_1_2, In18_1_3, In18_1_4, In18_1_5, In18_1_6, In19_1_1, In19_1_2, In20_1_1, &Out1_1_1, &Out1_1_2, &Out1_1_3, &Out1_1_4, &Out1_1_5, &Out1_1_6, &Out2_2_1, &Out2_2_2, &Out2_2_3, &Out2_2_4, &Out2_2_5, &Out2_2_6, &Out3_3_1, &Out3_3_2, &Out3_3_3, &Out3_3_4, &Out3_3_5, &Out3_3_6, &Out4_4_1, &Out4_4_2, &Out4_4_3, &Out5_5_1, &Out5_5_2, &Out5_5_3, &Out6_6_1, &Out6_6_2, &Out6_6_3, &Out7_7_1, &Out7_7_2, &Out7_7_3, &Out8_8_1, &Out8_8_2, &Out8_8_3, &Out8_8_4, &Out8_8_5, &Out8_8_6, &Out9_9_1, &Out9_9_2, &Out9_9_3, &Out9_9_4, &Out9_9_5, &Out9_9_6, &main_mem);
    _put_double("Out1_1_1", Out1_1_1);
    _put_double("Out1_1_2", Out1_1_2);
    _put_double("Out1_1_3", Out1_1_3);
    _put_double("Out1_1_4", Out1_1_4);
    _put_double("Out1_1_5", Out1_1_5);
    _put_double("Out1_1_6", Out1_1_6);
    _put_bool("Out2_2_1", Out2_2_1);
    _put_bool("Out2_2_2", Out2_2_2);
    _put_bool("Out2_2_3", Out2_2_3);
    _put_bool("Out2_2_4", Out2_2_4);
    _put_bool("Out2_2_5", Out2_2_5);
    _put_bool("Out2_2_6", Out2_2_6);
    _put_int("Out3_3_1", Out3_3_1);
    _put_int("Out3_3_2", Out3_3_2);
    _put_int("Out3_3_3", Out3_3_3);
    _put_int("Out3_3_4", Out3_3_4);
    _put_int("Out3_3_5", Out3_3_5);
    _put_int("Out3_3_6", Out3_3_6);
    _put_double("Out4_4_1", Out4_4_1);
    _put_double("Out4_4_2", Out4_4_2);
    _put_double("Out4_4_3", Out4_4_3);
    _put_bool("Out5_5_1", Out5_5_1);
    _put_bool("Out5_5_2", Out5_5_2);
    _put_bool("Out5_5_3", Out5_5_3);
    _put_int("Out6_6_1", Out6_6_1);
    _put_int("Out6_6_2", Out6_6_2);
    _put_int("Out6_6_3", Out6_6_3);
    _put_int("Out7_7_1", Out7_7_1);
    _put_int("Out7_7_2", Out7_7_2);
    _put_int("Out7_7_3", Out7_7_3);
    _put_int("Out8_8_1", Out8_8_1);
    _put_int("Out8_8_2", Out8_8_2);
    _put_int("Out8_8_3", Out8_8_3);
    _put_int("Out8_8_4", Out8_8_4);
    _put_int("Out8_8_5", Out8_8_5);
    _put_int("Out8_8_6", Out8_8_6);
    _put_int("Out9_9_1", Out9_9_1);
    _put_int("Out9_9_2", Out9_9_2);
    _put_int("Out9_9_3", Out9_9_3);
    _put_int("Out9_9_4", Out9_9_4);
    _put_int("Out9_9_5", Out9_9_5);
    _put_int("Out9_9_6", Out9_9_6);
  }
  return 1;
}
