#include <assert.h>
#include "assignment_port_test.h"

/* C code generated by lustrec
   SVN version number 1.1-Unversioned directory
   Code is C99 compliant */
   
/* Import dependencies */

/* Global constants (definitions) */

/* Struct definitions */
struct assignment_port_test_mem {struct _arrow_mem *ni_0; };


void assignment_port_test_reset (struct assignment_port_test_mem *self) {
  
  _arrow_reset(self->ni_0);
  return;
}

void assignment_port_test_step (double In1_1_1, double In1_1_2,
                                double In1_1_3, double In1_1_4,
                                double In1_1_5, double In1_1_6,
                                _Bool In2_1_1, _Bool In2_1_2, _Bool In2_1_3,
                                _Bool In2_1_4, _Bool In2_1_5, _Bool In2_1_6,
                                int In3_1_1, int In3_1_2, int In3_1_3,
                                int In3_1_4, int In3_1_5, int In3_1_6,
                                double In4_1_1, double In4_1_2,
                                double In4_1_3, _Bool In5_1_1, _Bool In5_1_2,
                                _Bool In5_1_3, int In6_1_1, int In6_1_2,
                                int In6_1_3, int In7_1_1, int In7_1_2,
                                int In7_1_3, int In8_1_1, int In8_1_2,
                                int In8_1_3, int In8_1_4, int In8_1_5,
                                int In8_1_6, double In9_1_1, double In9_1_2,
                                int In10_1_1, int In11_1_1, double In12_1_1,
                                double In12_1_2, double In13_1_1,
                                double In13_1_2, double In13_1_3,
                                double In14_1_1, double In14_1_2,
                                double In15_1_1, double In16_1_1,
                                double In17_1_1, int In18_1_1, int In18_1_2,
                                int In18_1_3, int In18_1_4, int In18_1_5,
                                int In18_1_6, double In19_1_1,
                                double In19_1_2, double In20_1_1, 
                                double (*Out1_1_1), double (*Out1_1_2),
                                double (*Out1_1_3), double (*Out1_1_4),
                                double (*Out1_1_5), double (*Out1_1_6),
                                _Bool (*Out2_2_1), _Bool (*Out2_2_2),
                                _Bool (*Out2_2_3), _Bool (*Out2_2_4),
                                _Bool (*Out2_2_5), _Bool (*Out2_2_6),
                                int (*Out3_3_1), int (*Out3_3_2),
                                int (*Out3_3_3), int (*Out3_3_4),
                                int (*Out3_3_5), int (*Out3_3_6),
                                double (*Out4_4_1), double (*Out4_4_2),
                                double (*Out4_4_3), _Bool (*Out5_5_1),
                                _Bool (*Out5_5_2), _Bool (*Out5_5_3),
                                int (*Out6_6_1), int (*Out6_6_2),
                                int (*Out6_6_3), int (*Out7_7_1),
                                int (*Out7_7_2), int (*Out7_7_3),
                                int (*Out8_8_1), int (*Out8_8_2),
                                int (*Out8_8_3), int (*Out8_8_4),
                                int (*Out8_8_5), int (*Out8_8_6),
                                int (*Out9_9_1), int (*Out9_9_2),
                                int (*Out9_9_3), int (*Out9_9_4),
                                int (*Out9_9_5), int (*Out9_9_6),
                                struct assignment_port_test_mem *self) {
  _Bool Assignment1_1_1;
  _Bool Assignment1_1_2;
  _Bool Assignment1_1_3;
  int Assignment2_1_1;
  int Assignment2_1_2;
  int Assignment2_1_3;
  int Assignment2_1_4;
  int Assignment2_1_5;
  int Assignment2_1_6;
  double Assignment3_1_1;
  double Assignment3_1_2;
  double Assignment3_1_3;
  _Bool Assignment4_1_1;
  _Bool Assignment4_1_2;
  _Bool Assignment4_1_3;
  int Assignment5_1_1;
  int Assignment5_1_2;
  int Assignment5_1_3;
  int Assignment6_1_1;
  int Assignment6_1_2;
  int Assignment6_1_3;
  int Assignment7_1_1;
  int Assignment7_1_2;
  int Assignment7_1_3;
  int Assignment7_1_4;
  int Assignment7_1_5;
  int Assignment7_1_6;
  int Assignment8_1_1;
  int Assignment8_1_2;
  int Assignment8_1_3;
  int Assignment8_1_4;
  int Assignment8_1_5;
  int Assignment8_1_6;
  double Assignment_1_2;
  double Assignment_1_5;
  _Bool __assignment_port_test_1;
  int __assignment_port_test_11;
  int __assignment_port_test_12;
  int __assignment_port_test_13;
  int __assignment_port_test_14;
  int __assignment_port_test_15;
  int __assignment_port_test_2;
  int __assignment_port_test_22;
  int __assignment_port_test_26;
  int __assignment_port_test_3;
  int __assignment_port_test_30;
  int __assignment_port_test_34;
  int __assignment_port_test_35;
  _Bool __assignment_port_test_39;
  int __assignment_port_test_4;
  _Bool __assignment_port_test_40;
  _Bool __assignment_port_test_41;
  int __assignment_port_test_45;
  int __assignment_port_test_46;
  double i_virtual_local;
  
  _arrow_step (1, 0, &__assignment_port_test_1, self->ni_0);
  if (__assignment_port_test_1) {
    i_virtual_local = 0.;
  } else {
    i_virtual_local = 1.;
  }
  Zero_step (In19_1_1, &__assignment_port_test_4);
  Zero_step (In19_1_2, &__assignment_port_test_3);
  Zero_step (In20_1_1, &__assignment_port_test_2);
  Zero_step (In9_1_1, &__assignment_port_test_46);
  Zero_step (In9_1_2, &__assignment_port_test_45);
  __assignment_port_test_41 = (In11_1_1 == 0);
  __assignment_port_test_40 = (In11_1_1 == 1);
  __assignment_port_test_39 = (In11_1_1 == 2);
  Zero_step (In14_1_1, &__assignment_port_test_35);
  Zero_step (In14_1_2, &__assignment_port_test_34);
  Zero_step (In15_1_1, &__assignment_port_test_30);
  Zero_step (In16_1_1, &__assignment_port_test_26);
  Zero_step (In17_1_1, &__assignment_port_test_22);
  Zero_step (In12_1_1, &__assignment_port_test_15);
  Zero_step (In13_1_1, &__assignment_port_test_14);
  Zero_step (In13_1_2, &__assignment_port_test_13);
  Zero_step (In12_1_2, &__assignment_port_test_12);
  Zero_step (In13_1_3, &__assignment_port_test_11);
  if ((((__assignment_port_test_4 == 2) && (__assignment_port_test_2 <= 3)) || ((__assignment_port_test_3 == 2) && (__assignment_port_test_2 <= 3)))) {
    Assignment8_1_6 = 7;
  } else {
    Assignment8_1_6 = In18_1_6;
  }
  *Out9_9_6 = Assignment8_1_6;
  if ((((__assignment_port_test_4 == 2) && (__assignment_port_test_2 <= 2)) || ((__assignment_port_test_3 == 2) && (__assignment_port_test_2 <= 2)))) {
    Assignment8_1_5 = 6;
  } else {
    Assignment8_1_5 = In18_1_5;
  }
  *Out9_9_5 = Assignment8_1_5;
  if ((((__assignment_port_test_4 == 2) && (__assignment_port_test_2 <= 1)) || ((__assignment_port_test_3 == 2) && (__assignment_port_test_2 <= 1)))) {
    Assignment8_1_4 = 5;
  } else {
    Assignment8_1_4 = In18_1_4;
  }
  *Out9_9_4 = Assignment8_1_4;
  if ((((__assignment_port_test_4 == 1) && (__assignment_port_test_2 <= 3)) || ((__assignment_port_test_3 == 1) && (__assignment_port_test_2 <= 3)))) {
    Assignment8_1_3 = 4;
  } else {
    Assignment8_1_3 = In18_1_3;
  }
  *Out9_9_3 = Assignment8_1_3;
  if ((((__assignment_port_test_4 == 1) && (__assignment_port_test_2 <= 2)) || ((__assignment_port_test_3 == 1) && (__assignment_port_test_2 <= 2)))) {
    Assignment8_1_2 = 3;
  } else {
    Assignment8_1_2 = In18_1_2;
  }
  *Out9_9_2 = Assignment8_1_2;
  if ((((__assignment_port_test_4 == 1) && (__assignment_port_test_2 <= 1)) || ((__assignment_port_test_3 == 1) && (__assignment_port_test_2 <= 1)))) {
    Assignment8_1_1 = 2;
  } else {
    Assignment8_1_1 = In18_1_1;
  }
  *Out9_9_1 = Assignment8_1_1;
  if ((((((((__assignment_port_test_15 == 2) && (__assignment_port_test_14 == 3)) || ((__assignment_port_test_15 == 2) && (__assignment_port_test_13 == 3))) || ((__assignment_port_test_15 == 2) && (__assignment_port_test_11 == 3))) || ((__assignment_port_test_12 == 2) && (__assignment_port_test_14 == 3))) || ((__assignment_port_test_12 == 2) && (__assignment_port_test_13 == 3))) || ((__assignment_port_test_12 == 2) && (__assignment_port_test_11 == 3)))) {
    Assignment7_1_6 = 7;
  } else {
    Assignment7_1_6 = In8_1_6;
  }
  *Out8_8_6 = Assignment7_1_6;
  if ((((((((__assignment_port_test_15 == 2) && (__assignment_port_test_14 == 2)) || ((__assignment_port_test_15 == 2) && (__assignment_port_test_13 == 2))) || ((__assignment_port_test_15 == 2) && (__assignment_port_test_11 == 2))) || ((__assignment_port_test_12 == 2) && (__assignment_port_test_14 == 2))) || ((__assignment_port_test_12 == 2) && (__assignment_port_test_13 == 2))) || ((__assignment_port_test_12 == 2) && (__assignment_port_test_11 == 2)))) {
    Assignment7_1_5 = 6;
  } else {
    Assignment7_1_5 = In8_1_5;
  }
  *Out8_8_5 = Assignment7_1_5;
  if ((((((((__assignment_port_test_15 == 2) && (__assignment_port_test_14 == 1)) || ((__assignment_port_test_15 == 2) && (__assignment_port_test_13 == 1))) || ((__assignment_port_test_15 == 2) && (__assignment_port_test_11 == 1))) || ((__assignment_port_test_12 == 2) && (__assignment_port_test_14 == 1))) || ((__assignment_port_test_12 == 2) && (__assignment_port_test_13 == 1))) || ((__assignment_port_test_12 == 2) && (__assignment_port_test_11 == 1)))) {
    Assignment7_1_4 = 5;
  } else {
    Assignment7_1_4 = In8_1_4;
  }
  *Out8_8_4 = Assignment7_1_4;
  if ((((((((__assignment_port_test_15 == 1) && (__assignment_port_test_14 == 3)) || ((__assignment_port_test_15 == 1) && (__assignment_port_test_13 == 3))) || ((__assignment_port_test_15 == 1) && (__assignment_port_test_11 == 3))) || ((__assignment_port_test_12 == 1) && (__assignment_port_test_14 == 3))) || ((__assignment_port_test_12 == 1) && (__assignment_port_test_13 == 3))) || ((__assignment_port_test_12 == 1) && (__assignment_port_test_11 == 3)))) {
    Assignment7_1_3 = 4;
  } else {
    Assignment7_1_3 = In8_1_3;
  }
  *Out8_8_3 = Assignment7_1_3;
  if ((((((((__assignment_port_test_15 == 1) && (__assignment_port_test_14 == 2)) || ((__assignment_port_test_15 == 1) && (__assignment_port_test_13 == 2))) || ((__assignment_port_test_15 == 1) && (__assignment_port_test_11 == 2))) || ((__assignment_port_test_12 == 1) && (__assignment_port_test_14 == 2))) || ((__assignment_port_test_12 == 1) && (__assignment_port_test_13 == 2))) || ((__assignment_port_test_12 == 1) && (__assignment_port_test_11 == 2)))) {
    Assignment7_1_2 = 3;
  } else {
    Assignment7_1_2 = In8_1_2;
  }
  *Out8_8_2 = Assignment7_1_2;
  if ((((((((__assignment_port_test_15 == 1) && (__assignment_port_test_14 == 1)) || ((__assignment_port_test_15 == 1) && (__assignment_port_test_13 == 1))) || ((__assignment_port_test_15 == 1) && (__assignment_port_test_11 == 1))) || ((__assignment_port_test_12 == 1) && (__assignment_port_test_14 == 1))) || ((__assignment_port_test_12 == 1) && (__assignment_port_test_13 == 1))) || ((__assignment_port_test_12 == 1) && (__assignment_port_test_11 == 1)))) {
    Assignment7_1_1 = 2;
  } else {
    Assignment7_1_1 = In8_1_1;
  }
  *Out8_8_1 = Assignment7_1_1;
  if ((__assignment_port_test_22 <= 3)) {
    Assignment6_1_3 = 4;
  } else {
    Assignment6_1_3 = In7_1_3;
  }
  *Out7_7_3 = Assignment6_1_3;
  if ((__assignment_port_test_22 <= 2)) {
    Assignment6_1_2 = 3;
  } else {
    Assignment6_1_2 = In7_1_2;
  }
  *Out7_7_2 = Assignment6_1_2;
  if ((__assignment_port_test_22 <= 1)) {
    Assignment6_1_1 = 2;
  } else {
    Assignment6_1_1 = In7_1_1;
  }
  *Out7_7_1 = Assignment6_1_1;
  if ((__assignment_port_test_26 == 3)) {
    Assignment5_1_3 = 12;
  } else {
    Assignment5_1_3 = In6_1_3;
  }
  *Out6_6_3 = Assignment5_1_3;
  if ((__assignment_port_test_26 == 2)) {
    Assignment5_1_2 = 12;
  } else {
    Assignment5_1_2 = In6_1_2;
  }
  *Out6_6_2 = Assignment5_1_2;
  if ((__assignment_port_test_26 == 1)) {
    Assignment5_1_1 = 12;
  } else {
    Assignment5_1_1 = In6_1_1;
  }
  *Out6_6_1 = Assignment5_1_1;
  if ((__assignment_port_test_30 == 2)) {
    Assignment4_1_3 = 1;
  } else {
    Assignment4_1_3 = In5_1_3;
  }
  *Out5_5_3 = Assignment4_1_3;
  if ((__assignment_port_test_30 == 1)) {
    Assignment4_1_2 = 1;
  } else {
    Assignment4_1_2 = In5_1_2;
  }
  *Out5_5_2 = Assignment4_1_2;
  if ((__assignment_port_test_30 == 0)) {
    Assignment4_1_1 = 1;
  } else {
    Assignment4_1_1 = In5_1_1;
  }
  *Out5_5_1 = Assignment4_1_1;
  if (((__assignment_port_test_35 == 3) || (__assignment_port_test_34 == 3))) {
    Assignment3_1_3 = 12.;
  } else {
    Assignment3_1_3 = In4_1_3;
  }
  *Out4_4_3 = Assignment3_1_3;
  if (((__assignment_port_test_35 == 2) || (__assignment_port_test_34 == 2))) {
    Assignment3_1_2 = 12.;
  } else {
    Assignment3_1_2 = In4_1_2;
  }
  *Out4_4_2 = Assignment3_1_2;
  if (((__assignment_port_test_35 == 1) || (__assignment_port_test_34 == 1))) {
    Assignment3_1_1 = 12.;
  } else {
    Assignment3_1_1 = In4_1_1;
  }
  *Out4_4_1 = Assignment3_1_1;
  if (__assignment_port_test_39) {
    Assignment2_1_6 = 12;
  } else {
    Assignment2_1_6 = In3_1_6;
  }
  *Out3_3_6 = Assignment2_1_6;
  if (__assignment_port_test_40) {
    Assignment2_1_5 = 12;
  } else {
    Assignment2_1_5 = In3_1_5;
  }
  *Out3_3_5 = Assignment2_1_5;
  if (__assignment_port_test_41) {
    Assignment2_1_4 = 12;
  } else {
    Assignment2_1_4 = In3_1_4;
  }
  *Out3_3_4 = Assignment2_1_4;
  if (__assignment_port_test_39) {
    Assignment2_1_3 = 12;
  } else {
    Assignment2_1_3 = In3_1_3;
  }
  *Out3_3_3 = Assignment2_1_3;
  if (__assignment_port_test_40) {
    Assignment2_1_2 = 12;
  } else {
    Assignment2_1_2 = In3_1_2;
  }
  *Out3_3_2 = Assignment2_1_2;
  if (__assignment_port_test_41) {
    Assignment2_1_1 = 12;
  } else {
    Assignment2_1_1 = In3_1_1;
  }
  *Out3_3_1 = Assignment2_1_1;
  *Out2_2_6 = In2_1_6;
  *Out2_2_5 = In2_1_5;
  *Out2_2_4 = In2_1_4;
  if ((In10_1_1 == 3)) {
    Assignment1_1_3 = 1;
  } else {
    Assignment1_1_3 = In2_1_3;
  }
  *Out2_2_3 = Assignment1_1_3;
  if ((In10_1_1 == 2)) {
    Assignment1_1_2 = 1;
  } else {
    Assignment1_1_2 = In2_1_2;
  }
  *Out2_2_2 = Assignment1_1_2;
  if ((In10_1_1 == 1)) {
    Assignment1_1_1 = 1;
  } else {
    Assignment1_1_1 = In2_1_1;
  }
  *Out2_2_1 = Assignment1_1_1;
  *Out1_1_6 = In1_1_6;
  if (((__assignment_port_test_46 == 2) || (__assignment_port_test_45 == 2))) {
    Assignment_1_5 = 12.;
  } else {
    Assignment_1_5 = In1_1_5;
  }
  *Out1_1_5 = Assignment_1_5;
  *Out1_1_4 = In1_1_4;
  *Out1_1_3 = In1_1_3;
  if (((__assignment_port_test_46 == 1) || (__assignment_port_test_45 == 1))) {
    Assignment_1_2 = 12.;
  } else {
    Assignment_1_2 = In1_1_2;
  }
  *Out1_1_2 = Assignment_1_2;
  *Out1_1_1 = In1_1_1;
  return;
}

void Zero_step (double In, 
                int (*Out)
                ) {
  
  *Out = 0;
  return;
}

