/* C code generated by lustrec
   SVN version number 1.1-Unversioned directory
   Code is C99 compliant */
   
#ifndef _ASSIGNMENT_PORT_TEST_alloc
#define _ASSIGNMENT_PORT_TEST_alloc

/* Import header from assignment_port_test */
#include "assignment_port_test.h"

/* Import dependencies */

/* Struct definitions */
struct assignment_port_test_mem {struct _arrow_mem *ni_0; };

/* Node allocation function/macro prototypes */
#define assignment_port_test_DECLARE(attr, inst)\
  attr struct assignment_port_test_mem inst;\
  _arrow_DECLARE(attr, inst ## _ni_0);
  
#define assignment_port_test_LINK(inst) do {\
  _arrow_LINK(inst ## _ni_0);\
  inst.ni_0 = &inst ## _ni_0;\
} while (0)

#define assignment_port_test_ALLOC(attr, inst)\
  assignment_port_test_DECLARE(attr, inst);\
  assignment_port_test_LINK(inst);



#endif

