/* C code generated by lustrec
   SVN version number 1.1-Unversioned directory
   Code is C99 compliant */
   
#ifndef _ASSIGNMENT_PORT_TEST
#define _ASSIGNMENT_PORT_TEST

/* Imports standard library */
#include "/usr/local/include/lustrec/arrow.h"


/* Import dependencies */

/* Types definitions */

/* Global constant (declarations, definitions are in C file) */

/* Struct declarations */
struct assignment_port_test_mem;

/* Nodes declarations */
extern void assignment_port_test_reset (struct assignment_port_test_mem *self);

extern void assignment_port_test_step (double In1_1_1, double In1_1_2,
                                       double In1_1_3, double In1_1_4,
                                       double In1_1_5, double In1_1_6,
                                       _Bool In2_1_1, _Bool In2_1_2,
                                       _Bool In2_1_3, _Bool In2_1_4,
                                       _Bool In2_1_5, _Bool In2_1_6,
                                       int In3_1_1, int In3_1_2, int In3_1_3,
                                       int In3_1_4, int In3_1_5, int In3_1_6,
                                       double In4_1_1, double In4_1_2,
                                       double In4_1_3, _Bool In5_1_1,
                                       _Bool In5_1_2, _Bool In5_1_3,
                                       int In6_1_1, int In6_1_2, int In6_1_3,
                                       int In7_1_1, int In7_1_2, int In7_1_3,
                                       int In8_1_1, int In8_1_2, int In8_1_3,
                                       int In8_1_4, int In8_1_5, int In8_1_6,
                                       double In9_1_1, double In9_1_2,
                                       int In10_1_1, int In11_1_1,
                                       double In12_1_1, double In12_1_2,
                                       double In13_1_1, double In13_1_2,
                                       double In13_1_3, double In14_1_1,
                                       double In14_1_2, double In15_1_1,
                                       double In16_1_1, double In17_1_1,
                                       int In18_1_1, int In18_1_2,
                                       int In18_1_3, int In18_1_4,
                                       int In18_1_5, int In18_1_6,
                                       double In19_1_1, double In19_1_2,
                                       double In20_1_1, 
                                       double (*Out1_1_1),
                                       double (*Out1_1_2),
                                       double (*Out1_1_3),
                                       double (*Out1_1_4),
                                       double (*Out1_1_5),
                                       double (*Out1_1_6), _Bool (*Out2_2_1),
                                       _Bool (*Out2_2_2), _Bool (*Out2_2_3),
                                       _Bool (*Out2_2_4), _Bool (*Out2_2_5),
                                       _Bool (*Out2_2_6), int (*Out3_3_1),
                                       int (*Out3_3_2), int (*Out3_3_3),
                                       int (*Out3_3_4), int (*Out3_3_5),
                                       int (*Out3_3_6), double (*Out4_4_1),
                                       double (*Out4_4_2),
                                       double (*Out4_4_3), _Bool (*Out5_5_1),
                                       _Bool (*Out5_5_2), _Bool (*Out5_5_3),
                                       int (*Out6_6_1), int (*Out6_6_2),
                                       int (*Out6_6_3), int (*Out7_7_1),
                                       int (*Out7_7_2), int (*Out7_7_3),
                                       int (*Out8_8_1), int (*Out8_8_2),
                                       int (*Out8_8_3), int (*Out8_8_4),
                                       int (*Out8_8_5), int (*Out8_8_6),
                                       int (*Out9_9_1), int (*Out9_9_2),
                                       int (*Out9_9_3), int (*Out9_9_4),
                                       int (*Out9_9_5), int (*Out9_9_6),
                                       struct assignment_port_test_mem *self);

extern void Zero_step (double In, 
                       int (*Out)
                       );


#endif

