#include <assert.h>
#include "relop_test.h"

/* C code generated by lustrec
   SVN version number 1.1-Unversioned directory
   Code is C99 compliant */
   
/* Import dependencies */

/* Global constants (definitions) */

/* Struct definitions */
struct relop_test_mem {struct _arrow_mem *ni_0; };


void relop_test_reset (struct relop_test_mem *self) {
  
  _arrow_reset(self->ni_0);
  return;
}

void relop_test_step (double In1_1_1, double In2_1_1, int In3_1_1,
                      int In4_1_1, _Bool In5_1_1, double In6_1_1,
                      double In7_1_1, double In8_1_1, int In9_1_1,
                      int In10_1_1, _Bool In11_1_1, _Bool In12_1_1,
                      double In13_1_1, double In14_1_1, int In15_1_1,
                      int In16_1_1, _Bool In17_1_1, _Bool In18_1_1,
                      double In19_1_1, double In20_1_1, int In21_1_1,
                      int In22_1_1, _Bool In23_1_1, _Bool In24_1_1,
                      double In25_1_1, double In26_1_1, int In27_1_1,
                      int In28_1_1, _Bool In29_1_1, _Bool In30_1_1,
                      double In31_1_1, double In32_1_1, int In33_1_1,
                      int In34_1_1, _Bool In35_1_1, _Bool In36_1_1, 
                      _Bool (*Out1_1_1), _Bool (*Out2_2_1),
                      _Bool (*Out3_3_1), _Bool (*Out4_4_1),
                      _Bool (*Out5_5_1), _Bool (*Out6_6_1),
                      _Bool (*Out7_7_1), _Bool (*Out8_8_1),
                      _Bool (*Out9_9_1), _Bool (*Out10_10_1),
                      _Bool (*Out11_11_1), _Bool (*Out12_12_1),
                      _Bool (*Out13_13_1), _Bool (*Out14_14_1),
                      _Bool (*Out15_15_1), _Bool (*Out16_16_1),
                      _Bool (*Out17_17_1), _Bool (*Out18_18_1),
                      struct relop_test_mem *self) {
  _Bool __relop_test_1;
  int __relop_test_10;
  int __relop_test_11;
  int __relop_test_12;
  int __relop_test_2;
  int __relop_test_3;
  int __relop_test_4;
  int __relop_test_5;
  double __relop_test_6;
  int __relop_test_7;
  int __relop_test_8;
  int __relop_test_9;
  double i_virtual_local;
  
  _arrow_step (1, 0, &__relop_test_1, self->ni_0);
  if (__relop_test_1) {
    i_virtual_local = 0.;
  } else {
    i_virtual_local = 1.;
  }
  if (In30_1_1) {
    __relop_test_9 = 1;
  } else {
    __relop_test_9 = 0;
  }
  if (In35_1_1) {
    __relop_test_8 = 1;
  } else {
    __relop_test_8 = 0;
  }
  if (In36_1_1) {
    __relop_test_7 = 1;
  } else {
    __relop_test_7 = 0;
  }
  if (In5_1_1) {
    __relop_test_6 = 1.;
  } else {
    __relop_test_6 = 0.;
  }
  if (In11_1_1) {
    __relop_test_5 = 1;
  } else {
    __relop_test_5 = 0;
  }
  if (In12_1_1) {
    __relop_test_4 = 1;
  } else {
    __relop_test_4 = 0;
  }
  if (In17_1_1) {
    __relop_test_3 = 1;
  } else {
    __relop_test_3 = 0;
  }
  if (In18_1_1) {
    __relop_test_2 = 1;
  } else {
    __relop_test_2 = 0;
  }
  if (In23_1_1) {
    __relop_test_12 = 1;
  } else {
    __relop_test_12 = 0;
  }
  if (In24_1_1) {
    __relop_test_11 = 1;
  } else {
    __relop_test_11 = 0;
  }
  if (In29_1_1) {
    __relop_test_10 = 1;
  } else {
    __relop_test_10 = 0;
  }
  *Out9_9_1 = (!(__relop_test_3 == __relop_test_2));
  *Out8_8_1 = (!(In15_1_1 == In16_1_1));
  *Out7_7_1 = (!(In13_1_1 == In14_1_1));
  *Out6_6_1 = (__relop_test_5 == __relop_test_4);
  *Out5_5_1 = (In9_1_1 == In10_1_1);
  *Out4_4_1 = (In7_1_1 == In8_1_1);
  *Out3_3_1 = (__relop_test_6 <= In6_1_1);
  *Out2_2_1 = (In3_1_1 <= In4_1_1);
  *Out1_1_1 = (In1_1_1 <= In2_1_1);
  *Out18_18_1 = (__relop_test_8 > __relop_test_7);
  *Out17_17_1 = (In33_1_1 > In34_1_1);
  *Out16_16_1 = (In31_1_1 > In32_1_1);
  *Out15_15_1 = (__relop_test_10 >= __relop_test_9);
  *Out14_14_1 = (In27_1_1 >= In28_1_1);
  *Out13_13_1 = (In25_1_1 >= In26_1_1);
  *Out12_12_1 = (__relop_test_12 < __relop_test_11);
  *Out11_11_1 = (In21_1_1 < In22_1_1);
  *Out10_10_1 = (In19_1_1 < In20_1_1);
  return;
}

