#include <stdio.h>
#include <unistd.h>
#include "/usr/local/include/lustrec/io_frontend.h"
#include <stdlib.h>
#include <assert.h>
#include "relop_test_alloc.h"

/* C code generated by lustrec
   SVN version number 1.1-Unversioned directory
   Code is C99 compliant */
   
int main (int argc, char *argv[]) {
  /* Declaration of inputs/outputs variables */
  double In1_1_1 = 0.;
  double In2_1_1 = 0.;
  int In3_1_1 = 0;
  int In4_1_1 = 0;
  _Bool In5_1_1 = 0;
  double In6_1_1 = 0.;
  double In7_1_1 = 0.;
  double In8_1_1 = 0.;
  int In9_1_1 = 0;
  int In10_1_1 = 0;
  _Bool In11_1_1 = 0;
  _Bool In12_1_1 = 0;
  double In13_1_1 = 0.;
  double In14_1_1 = 0.;
  int In15_1_1 = 0;
  int In16_1_1 = 0;
  _Bool In17_1_1 = 0;
  _Bool In18_1_1 = 0;
  double In19_1_1 = 0.;
  double In20_1_1 = 0.;
  int In21_1_1 = 0;
  int In22_1_1 = 0;
  _Bool In23_1_1 = 0;
  _Bool In24_1_1 = 0;
  double In25_1_1 = 0.;
  double In26_1_1 = 0.;
  int In27_1_1 = 0;
  int In28_1_1 = 0;
  _Bool In29_1_1 = 0;
  _Bool In30_1_1 = 0;
  double In31_1_1 = 0.;
  double In32_1_1 = 0.;
  int In33_1_1 = 0;
  int In34_1_1 = 0;
  _Bool In35_1_1 = 0;
  _Bool In36_1_1 = 0;
  _Bool Out1_1_1 = 0;
  _Bool Out2_2_1 = 0;
  _Bool Out3_3_1 = 0;
  _Bool Out4_4_1 = 0;
  _Bool Out5_5_1 = 0;
  _Bool Out6_6_1 = 0;
  _Bool Out7_7_1 = 0;
  _Bool Out8_8_1 = 0;
  _Bool Out9_9_1 = 0;
  _Bool Out10_10_1 = 0;
  _Bool Out11_11_1 = 0;
  _Bool Out12_12_1 = 0;
  _Bool Out13_13_1 = 0;
  _Bool Out14_14_1 = 0;
  _Bool Out15_15_1 = 0;
  _Bool Out16_16_1 = 0;
  _Bool Out17_17_1 = 0;
  _Bool Out18_18_1 = 0;
  
  /* Main memory allocation */
  relop_test_ALLOC(static,main_mem);
  
  /* Initialize the main memory */
  relop_test_reset(&main_mem);
  
  ISATTY = isatty(0);
  
  /* Infinite loop */
  while(1){
    fflush(stdout);
    In1_1_1 = _get_double("In1_1_1");
    In2_1_1 = _get_double("In2_1_1");
    In3_1_1 = _get_int("In3_1_1");
    In4_1_1 = _get_int("In4_1_1");
    In5_1_1 = _get_bool("In5_1_1");
    In6_1_1 = _get_double("In6_1_1");
    In7_1_1 = _get_double("In7_1_1");
    In8_1_1 = _get_double("In8_1_1");
    In9_1_1 = _get_int("In9_1_1");
    In10_1_1 = _get_int("In10_1_1");
    In11_1_1 = _get_bool("In11_1_1");
    In12_1_1 = _get_bool("In12_1_1");
    In13_1_1 = _get_double("In13_1_1");
    In14_1_1 = _get_double("In14_1_1");
    In15_1_1 = _get_int("In15_1_1");
    In16_1_1 = _get_int("In16_1_1");
    In17_1_1 = _get_bool("In17_1_1");
    In18_1_1 = _get_bool("In18_1_1");
    In19_1_1 = _get_double("In19_1_1");
    In20_1_1 = _get_double("In20_1_1");
    In21_1_1 = _get_int("In21_1_1");
    In22_1_1 = _get_int("In22_1_1");
    In23_1_1 = _get_bool("In23_1_1");
    In24_1_1 = _get_bool("In24_1_1");
    In25_1_1 = _get_double("In25_1_1");
    In26_1_1 = _get_double("In26_1_1");
    In27_1_1 = _get_int("In27_1_1");
    In28_1_1 = _get_int("In28_1_1");
    In29_1_1 = _get_bool("In29_1_1");
    In30_1_1 = _get_bool("In30_1_1");
    In31_1_1 = _get_double("In31_1_1");
    In32_1_1 = _get_double("In32_1_1");
    In33_1_1 = _get_int("In33_1_1");
    In34_1_1 = _get_int("In34_1_1");
    In35_1_1 = _get_bool("In35_1_1");
    In36_1_1 = _get_bool("In36_1_1");
    relop_test_step(In1_1_1, In2_1_1, In3_1_1, In4_1_1, In5_1_1, In6_1_1, In7_1_1, In8_1_1, In9_1_1, In10_1_1, In11_1_1, In12_1_1, In13_1_1, In14_1_1, In15_1_1, In16_1_1, In17_1_1, In18_1_1, In19_1_1, In20_1_1, In21_1_1, In22_1_1, In23_1_1, In24_1_1, In25_1_1, In26_1_1, In27_1_1, In28_1_1, In29_1_1, In30_1_1, In31_1_1, In32_1_1, In33_1_1, In34_1_1, In35_1_1, In36_1_1, &Out1_1_1, &Out2_2_1, &Out3_3_1, &Out4_4_1, &Out5_5_1, &Out6_6_1, &Out7_7_1, &Out8_8_1, &Out9_9_1, &Out10_10_1, &Out11_11_1, &Out12_12_1, &Out13_13_1, &Out14_14_1, &Out15_15_1, &Out16_16_1, &Out17_17_1, &Out18_18_1, &main_mem);
    _put_bool("Out1_1_1", Out1_1_1);
    _put_bool("Out2_2_1", Out2_2_1);
    _put_bool("Out3_3_1", Out3_3_1);
    _put_bool("Out4_4_1", Out4_4_1);
    _put_bool("Out5_5_1", Out5_5_1);
    _put_bool("Out6_6_1", Out6_6_1);
    _put_bool("Out7_7_1", Out7_7_1);
    _put_bool("Out8_8_1", Out8_8_1);
    _put_bool("Out9_9_1", Out9_9_1);
    _put_bool("Out10_10_1", Out10_10_1);
    _put_bool("Out11_11_1", Out11_11_1);
    _put_bool("Out12_12_1", Out12_12_1);
    _put_bool("Out13_13_1", Out13_13_1);
    _put_bool("Out14_14_1", Out14_14_1);
    _put_bool("Out15_15_1", Out15_15_1);
    _put_bool("Out16_16_1", Out16_16_1);
    _put_bool("Out17_17_1", Out17_17_1);
    _put_bool("Out18_18_1", Out18_18_1);
  }
  return 1;
}
