/* C code generated by lustrec
   SVN version number 1.1-Unversioned directory
   Code is C99 compliant */
   
#ifndef _RELOP_TEST
#define _RELOP_TEST

/* Imports standard library */
#include "/usr/local/include/lustrec/arrow.h"


/* Import dependencies */

/* Types definitions */

/* Global constant (declarations, definitions are in C file) */

/* Struct declarations */
struct relop_test_mem;

/* Nodes declarations */
extern void relop_test_reset (struct relop_test_mem *self);

extern void relop_test_step (double In1_1_1, double In2_1_1, int In3_1_1,
                             int In4_1_1, _Bool In5_1_1, double In6_1_1,
                             double In7_1_1, double In8_1_1, int In9_1_1,
                             int In10_1_1, _Bool In11_1_1, _Bool In12_1_1,
                             double In13_1_1, double In14_1_1, int In15_1_1,
                             int In16_1_1, _Bool In17_1_1, _Bool In18_1_1,
                             double In19_1_1, double In20_1_1, int In21_1_1,
                             int In22_1_1, _Bool In23_1_1, _Bool In24_1_1,
                             double In25_1_1, double In26_1_1, int In27_1_1,
                             int In28_1_1, _Bool In29_1_1, _Bool In30_1_1,
                             double In31_1_1, double In32_1_1, int In33_1_1,
                             int In34_1_1, _Bool In35_1_1, _Bool In36_1_1, 
                             _Bool (*Out1_1_1), _Bool (*Out2_2_1),
                             _Bool (*Out3_3_1), _Bool (*Out4_4_1),
                             _Bool (*Out5_5_1), _Bool (*Out6_6_1),
                             _Bool (*Out7_7_1), _Bool (*Out8_8_1),
                             _Bool (*Out9_9_1), _Bool (*Out10_10_1),
                             _Bool (*Out11_11_1), _Bool (*Out12_12_1),
                             _Bool (*Out13_13_1), _Bool (*Out14_14_1),
                             _Bool (*Out15_15_1), _Bool (*Out16_16_1),
                             _Bool (*Out17_17_1), _Bool (*Out18_18_1),
                             struct relop_test_mem *self);


#endif

