#include <assert.h>
#include "multiportswitch_test.h"

/* C code generated by lustrec
   SVN version number 1.1-Unversioned directory
   Code is C99 compliant */
   
/* Import dependencies */

/* Global constants (definitions) */

/* Struct definitions */
struct multiportswitch_test_mem {struct _arrow_mem *ni_0; };


void multiportswitch_test_reset (struct multiportswitch_test_mem *self) {
  
  _arrow_reset(self->ni_0);
  return;
}

void multiportswitch_test_step (double In2_1_1, double In2_1_2,
                                double In2_1_3, double In2_1_4,
                                double In2_1_5, double In2_1_6,
                                double In3_1_1, double In4_1_1,
                                double In4_1_2, double In4_1_3,
                                double In4_1_4, double In4_1_5,
                                double In4_1_6, int In1_1_1, int In1_1_2,
                                int In1_1_3, int In1_1_4, int In1_1_5,
                                int In1_1_6, double In5_1_1, double In6_1_1,
                                double In7_1_1, int In8_1_1, double In9_1_1,
                                double In10_1_1, double In11_1_1,
                                int In12_1_1, double In13_1_1,
                                double In13_1_2, double In13_1_3,
                                double In13_1_4, double In13_1_5,
                                double In13_1_6, double In14_1_1,
                                int In16_1_1, int In16_1_2, int In16_1_3,
                                int In16_1_4, int In16_1_5, int In16_1_6,
                                double In17_1_1, double In18_1_1,
                                int In20_1_1, double In21_1_1,
                                double In22_1_1, int In24_1_1,
                                double In15_1_1, int In25_1_1,
                                double In19_1_1, double In19_1_2,
                                double In19_1_3, int In23_1_1, 
                                double (*Out1_1_1), double (*Out1_1_2),
                                double (*Out1_1_3), double (*Out1_1_4),
                                double (*Out1_1_5), double (*Out1_1_6),
                                double (*Out2_2_1), double (*Out3_3_1),
                                double (*Out4_4_1), double (*Out4_4_2),
                                double (*Out4_4_3), double (*Out4_4_4),
                                double (*Out4_4_5), double (*Out4_4_6),
                                double (*Out5_5_1), double (*Out6_6_1),
                                double (*Out7_7_1), double (*Out8_8_1),
                                struct multiportswitch_test_mem *self) {
  double MultiportSwitch1_1_1;
  double MultiportSwitch2_1_1;
  double MultiportSwitch3_1_1;
  double MultiportSwitch3_1_2;
  double MultiportSwitch3_1_3;
  double MultiportSwitch3_1_4;
  double MultiportSwitch3_1_5;
  double MultiportSwitch3_1_6;
  double MultiportSwitch4_1_1;
  double MultiportSwitch5_1_1;
  double MultiportSwitch7_1_1;
  double MultiportSwitch_1_1;
  double MultiportSwitch_1_2;
  double MultiportSwitch_1_3;
  double MultiportSwitch_1_4;
  double MultiportSwitch_1_5;
  double MultiportSwitch_1_6;
  _Bool __multiportswitch_test_1;
  double i_virtual_local;
  
  _arrow_step (1, 0, &__multiportswitch_test_1, self->ni_0);
  if (__multiportswitch_test_1) {
    i_virtual_local = 0.;
  } else {
    i_virtual_local = 1.;
  }
  if ((In23_1_1 == 0)) {
    MultiportSwitch7_1_1 = In19_1_1;
  } else {
    if ((In23_1_1 == 1)) {
      MultiportSwitch7_1_1 = In19_1_2;
    } else {
      MultiportSwitch7_1_1 = In19_1_3;
    }
  }
  *Out8_8_1 = MultiportSwitch7_1_1;
  *Out7_7_1 = In15_1_1;
  if ((In24_1_1 == 1)) {
    MultiportSwitch5_1_1 = In21_1_1;
  } else {
    MultiportSwitch5_1_1 = In22_1_1;
  }
  *Out6_6_1 = MultiportSwitch5_1_1;
  if ((In20_1_1 == 0)) {
    MultiportSwitch4_1_1 = In17_1_1;
  } else {
    MultiportSwitch4_1_1 = In18_1_1;
  }
  *Out5_5_1 = MultiportSwitch4_1_1;
  if ((In16_1_6 == 1)) {
    MultiportSwitch3_1_6 = In13_1_6;
  } else {
    MultiportSwitch3_1_6 = In14_1_1;
  }
  *Out4_4_6 = MultiportSwitch3_1_6;
  if ((In16_1_5 == 1)) {
    MultiportSwitch3_1_5 = In13_1_5;
  } else {
    MultiportSwitch3_1_5 = In14_1_1;
  }
  *Out4_4_5 = MultiportSwitch3_1_5;
  if ((In16_1_4 == 1)) {
    MultiportSwitch3_1_4 = In13_1_4;
  } else {
    MultiportSwitch3_1_4 = In14_1_1;
  }
  *Out4_4_4 = MultiportSwitch3_1_4;
  if ((In16_1_3 == 1)) {
    MultiportSwitch3_1_3 = In13_1_3;
  } else {
    MultiportSwitch3_1_3 = In14_1_1;
  }
  *Out4_4_3 = MultiportSwitch3_1_3;
  if ((In16_1_2 == 1)) {
    MultiportSwitch3_1_2 = In13_1_2;
  } else {
    MultiportSwitch3_1_2 = In14_1_1;
  }
  *Out4_4_2 = MultiportSwitch3_1_2;
  if ((In16_1_1 == 1)) {
    MultiportSwitch3_1_1 = In13_1_1;
  } else {
    MultiportSwitch3_1_1 = In14_1_1;
  }
  *Out4_4_1 = MultiportSwitch3_1_1;
  if ((In12_1_1 == 1)) {
    MultiportSwitch2_1_1 = In9_1_1;
  } else {
    if ((In12_1_1 == 2)) {
      MultiportSwitch2_1_1 = In10_1_1;
    } else {
      MultiportSwitch2_1_1 = In11_1_1;
    }
  }
  *Out3_3_1 = MultiportSwitch2_1_1;
  if ((In8_1_1 == 0)) {
    MultiportSwitch1_1_1 = In5_1_1;
  } else {
    if ((In8_1_1 == 1)) {
      MultiportSwitch1_1_1 = In6_1_1;
    } else {
      MultiportSwitch1_1_1 = In7_1_1;
    }
  }
  *Out2_2_1 = MultiportSwitch1_1_1;
  if ((In1_1_6 == 1)) {
    MultiportSwitch_1_6 = In2_1_6;
  } else {
    if ((In1_1_6 == 2)) {
      MultiportSwitch_1_6 = In3_1_1;
    } else {
      if ((In1_1_6 == 3)) {
        MultiportSwitch_1_6 = In3_1_1;
      } else {
        MultiportSwitch_1_6 = In4_1_6;
      }
    }
  }
  *Out1_1_6 = MultiportSwitch_1_6;
  if ((In1_1_5 == 1)) {
    MultiportSwitch_1_5 = In2_1_5;
  } else {
    if ((In1_1_5 == 2)) {
      MultiportSwitch_1_5 = In3_1_1;
    } else {
      if ((In1_1_5 == 3)) {
        MultiportSwitch_1_5 = In3_1_1;
      } else {
        MultiportSwitch_1_5 = In4_1_5;
      }
    }
  }
  *Out1_1_5 = MultiportSwitch_1_5;
  if ((In1_1_4 == 1)) {
    MultiportSwitch_1_4 = In2_1_4;
  } else {
    if ((In1_1_4 == 2)) {
      MultiportSwitch_1_4 = In3_1_1;
    } else {
      if ((In1_1_4 == 3)) {
        MultiportSwitch_1_4 = In3_1_1;
      } else {
        MultiportSwitch_1_4 = In4_1_4;
      }
    }
  }
  *Out1_1_4 = MultiportSwitch_1_4;
  if ((In1_1_3 == 1)) {
    MultiportSwitch_1_3 = In2_1_3;
  } else {
    if ((In1_1_3 == 2)) {
      MultiportSwitch_1_3 = In3_1_1;
    } else {
      if ((In1_1_3 == 3)) {
        MultiportSwitch_1_3 = In3_1_1;
      } else {
        MultiportSwitch_1_3 = In4_1_3;
      }
    }
  }
  *Out1_1_3 = MultiportSwitch_1_3;
  if ((In1_1_2 == 1)) {
    MultiportSwitch_1_2 = In2_1_2;
  } else {
    if ((In1_1_2 == 2)) {
      MultiportSwitch_1_2 = In3_1_1;
    } else {
      if ((In1_1_2 == 3)) {
        MultiportSwitch_1_2 = In3_1_1;
      } else {
        MultiportSwitch_1_2 = In4_1_2;
      }
    }
  }
  *Out1_1_2 = MultiportSwitch_1_2;
  if ((In1_1_1 == 1)) {
    MultiportSwitch_1_1 = In2_1_1;
  } else {
    if ((In1_1_1 == 2)) {
      MultiportSwitch_1_1 = In3_1_1;
    } else {
      if ((In1_1_1 == 3)) {
        MultiportSwitch_1_1 = In3_1_1;
      } else {
        MultiportSwitch_1_1 = In4_1_1;
      }
    }
  }
  *Out1_1_1 = MultiportSwitch_1_1;
  return;
}

