#include <stdio.h>
#include <unistd.h>
#include "/usr/local/include/lustrec/io_frontend.h"
#include <stdlib.h>
#include <assert.h>
#include "multiportswitch_test_alloc.h"

/* C code generated by lustrec
   SVN version number 1.1-Unversioned directory
   Code is C99 compliant */
   
int main (int argc, char *argv[]) {
  /* Declaration of inputs/outputs variables */
  double In2_1_1 = 0.;
  double In2_1_2 = 0.;
  double In2_1_3 = 0.;
  double In2_1_4 = 0.;
  double In2_1_5 = 0.;
  double In2_1_6 = 0.;
  double In3_1_1 = 0.;
  double In4_1_1 = 0.;
  double In4_1_2 = 0.;
  double In4_1_3 = 0.;
  double In4_1_4 = 0.;
  double In4_1_5 = 0.;
  double In4_1_6 = 0.;
  int In1_1_1 = 0;
  int In1_1_2 = 0;
  int In1_1_3 = 0;
  int In1_1_4 = 0;
  int In1_1_5 = 0;
  int In1_1_6 = 0;
  double In5_1_1 = 0.;
  double In6_1_1 = 0.;
  double In7_1_1 = 0.;
  int In8_1_1 = 0;
  double In9_1_1 = 0.;
  double In10_1_1 = 0.;
  double In11_1_1 = 0.;
  int In12_1_1 = 0;
  double In13_1_1 = 0.;
  double In13_1_2 = 0.;
  double In13_1_3 = 0.;
  double In13_1_4 = 0.;
  double In13_1_5 = 0.;
  double In13_1_6 = 0.;
  double In14_1_1 = 0.;
  int In16_1_1 = 0;
  int In16_1_2 = 0;
  int In16_1_3 = 0;
  int In16_1_4 = 0;
  int In16_1_5 = 0;
  int In16_1_6 = 0;
  double In17_1_1 = 0.;
  double In18_1_1 = 0.;
  int In20_1_1 = 0;
  double In21_1_1 = 0.;
  double In22_1_1 = 0.;
  int In24_1_1 = 0;
  double In15_1_1 = 0.;
  int In25_1_1 = 0;
  double In19_1_1 = 0.;
  double In19_1_2 = 0.;
  double In19_1_3 = 0.;
  int In23_1_1 = 0;
  double Out1_1_1 = 0.;
  double Out1_1_2 = 0.;
  double Out1_1_3 = 0.;
  double Out1_1_4 = 0.;
  double Out1_1_5 = 0.;
  double Out1_1_6 = 0.;
  double Out2_2_1 = 0.;
  double Out3_3_1 = 0.;
  double Out4_4_1 = 0.;
  double Out4_4_2 = 0.;
  double Out4_4_3 = 0.;
  double Out4_4_4 = 0.;
  double Out4_4_5 = 0.;
  double Out4_4_6 = 0.;
  double Out5_5_1 = 0.;
  double Out6_6_1 = 0.;
  double Out7_7_1 = 0.;
  double Out8_8_1 = 0.;
  
  /* Main memory allocation */
  multiportswitch_test_ALLOC(static,main_mem);
  
  /* Initialize the main memory */
  multiportswitch_test_reset(&main_mem);
  
  ISATTY = isatty(0);
  
  /* Infinite loop */
  while(1){
    fflush(stdout);
    In2_1_1 = _get_double("In2_1_1");
    In2_1_2 = _get_double("In2_1_2");
    In2_1_3 = _get_double("In2_1_3");
    In2_1_4 = _get_double("In2_1_4");
    In2_1_5 = _get_double("In2_1_5");
    In2_1_6 = _get_double("In2_1_6");
    In3_1_1 = _get_double("In3_1_1");
    In4_1_1 = _get_double("In4_1_1");
    In4_1_2 = _get_double("In4_1_2");
    In4_1_3 = _get_double("In4_1_3");
    In4_1_4 = _get_double("In4_1_4");
    In4_1_5 = _get_double("In4_1_5");
    In4_1_6 = _get_double("In4_1_6");
    In1_1_1 = _get_int("In1_1_1");
    In1_1_2 = _get_int("In1_1_2");
    In1_1_3 = _get_int("In1_1_3");
    In1_1_4 = _get_int("In1_1_4");
    In1_1_5 = _get_int("In1_1_5");
    In1_1_6 = _get_int("In1_1_6");
    In5_1_1 = _get_double("In5_1_1");
    In6_1_1 = _get_double("In6_1_1");
    In7_1_1 = _get_double("In7_1_1");
    In8_1_1 = _get_int("In8_1_1");
    In9_1_1 = _get_double("In9_1_1");
    In10_1_1 = _get_double("In10_1_1");
    In11_1_1 = _get_double("In11_1_1");
    In12_1_1 = _get_int("In12_1_1");
    In13_1_1 = _get_double("In13_1_1");
    In13_1_2 = _get_double("In13_1_2");
    In13_1_3 = _get_double("In13_1_3");
    In13_1_4 = _get_double("In13_1_4");
    In13_1_5 = _get_double("In13_1_5");
    In13_1_6 = _get_double("In13_1_6");
    In14_1_1 = _get_double("In14_1_1");
    In16_1_1 = _get_int("In16_1_1");
    In16_1_2 = _get_int("In16_1_2");
    In16_1_3 = _get_int("In16_1_3");
    In16_1_4 = _get_int("In16_1_4");
    In16_1_5 = _get_int("In16_1_5");
    In16_1_6 = _get_int("In16_1_6");
    In17_1_1 = _get_double("In17_1_1");
    In18_1_1 = _get_double("In18_1_1");
    In20_1_1 = _get_int("In20_1_1");
    In21_1_1 = _get_double("In21_1_1");
    In22_1_1 = _get_double("In22_1_1");
    In24_1_1 = _get_int("In24_1_1");
    In15_1_1 = _get_double("In15_1_1");
    In25_1_1 = _get_int("In25_1_1");
    In19_1_1 = _get_double("In19_1_1");
    In19_1_2 = _get_double("In19_1_2");
    In19_1_3 = _get_double("In19_1_3");
    In23_1_1 = _get_int("In23_1_1");
    multiportswitch_test_step(In2_1_1, In2_1_2, In2_1_3, In2_1_4, In2_1_5, In2_1_6, In3_1_1, In4_1_1, In4_1_2, In4_1_3, In4_1_4, In4_1_5, In4_1_6, In1_1_1, In1_1_2, In1_1_3, In1_1_4, In1_1_5, In1_1_6, In5_1_1, In6_1_1, In7_1_1, In8_1_1, In9_1_1, In10_1_1, In11_1_1, In12_1_1, In13_1_1, In13_1_2, In13_1_3, In13_1_4, In13_1_5, In13_1_6, In14_1_1, In16_1_1, In16_1_2, In16_1_3, In16_1_4, In16_1_5, In16_1_6, In17_1_1, In18_1_1, In20_1_1, In21_1_1, In22_1_1, In24_1_1, In15_1_1, In25_1_1, In19_1_1, In19_1_2, In19_1_3, In23_1_1, &Out1_1_1, &Out1_1_2, &Out1_1_3, &Out1_1_4, &Out1_1_5, &Out1_1_6, &Out2_2_1, &Out3_3_1, &Out4_4_1, &Out4_4_2, &Out4_4_3, &Out4_4_4, &Out4_4_5, &Out4_4_6, &Out5_5_1, &Out6_6_1, &Out7_7_1, &Out8_8_1, &main_mem);
    _put_double("Out1_1_1", Out1_1_1);
    _put_double("Out1_1_2", Out1_1_2);
    _put_double("Out1_1_3", Out1_1_3);
    _put_double("Out1_1_4", Out1_1_4);
    _put_double("Out1_1_5", Out1_1_5);
    _put_double("Out1_1_6", Out1_1_6);
    _put_double("Out2_2_1", Out2_2_1);
    _put_double("Out3_3_1", Out3_3_1);
    _put_double("Out4_4_1", Out4_4_1);
    _put_double("Out4_4_2", Out4_4_2);
    _put_double("Out4_4_3", Out4_4_3);
    _put_double("Out4_4_4", Out4_4_4);
    _put_double("Out4_4_5", Out4_4_5);
    _put_double("Out4_4_6", Out4_4_6);
    _put_double("Out5_5_1", Out5_5_1);
    _put_double("Out6_6_1", Out6_6_1);
    _put_double("Out7_7_1", Out7_7_1);
    _put_double("Out8_8_1", Out8_8_1);
  }
  return 1;
}
