/* C code generated by lustrec
   SVN version number 1.1-Unversioned directory
   Code is C99 compliant */
   
#ifndef _MULTIPORTSWITCH_TEST
#define _MULTIPORTSWITCH_TEST

/* Imports standard library */
#include "/usr/local/include/lustrec/arrow.h"


/* Import dependencies */

/* Types definitions */

/* Global constant (declarations, definitions are in C file) */

/* Struct declarations */
struct multiportswitch_test_mem;

/* Nodes declarations */
extern void multiportswitch_test_reset (struct multiportswitch_test_mem *self);

extern void multiportswitch_test_step (double In2_1_1, double In2_1_2,
                                       double In2_1_3, double In2_1_4,
                                       double In2_1_5, double In2_1_6,
                                       double In3_1_1, double In4_1_1,
                                       double In4_1_2, double In4_1_3,
                                       double In4_1_4, double In4_1_5,
                                       double In4_1_6, int In1_1_1,
                                       int In1_1_2, int In1_1_3, int In1_1_4,
                                       int In1_1_5, int In1_1_6,
                                       double In5_1_1, double In6_1_1,
                                       double In7_1_1, int In8_1_1,
                                       double In9_1_1, double In10_1_1,
                                       double In11_1_1, int In12_1_1,
                                       double In13_1_1, double In13_1_2,
                                       double In13_1_3, double In13_1_4,
                                       double In13_1_5, double In13_1_6,
                                       double In14_1_1, int In16_1_1,
                                       int In16_1_2, int In16_1_3,
                                       int In16_1_4, int In16_1_5,
                                       int In16_1_6, double In17_1_1,
                                       double In18_1_1, int In20_1_1,
                                       double In21_1_1, double In22_1_1,
                                       int In24_1_1, double In15_1_1,
                                       int In25_1_1, double In19_1_1,
                                       double In19_1_2, double In19_1_3,
                                       int In23_1_1, 
                                       double (*Out1_1_1),
                                       double (*Out1_1_2),
                                       double (*Out1_1_3),
                                       double (*Out1_1_4),
                                       double (*Out1_1_5),
                                       double (*Out1_1_6),
                                       double (*Out2_2_1),
                                       double (*Out3_3_1),
                                       double (*Out4_4_1),
                                       double (*Out4_4_2),
                                       double (*Out4_4_3),
                                       double (*Out4_4_4),
                                       double (*Out4_4_5),
                                       double (*Out4_4_6),
                                       double (*Out5_5_1),
                                       double (*Out6_6_1),
                                       double (*Out7_7_1), double (*Out8_8_1),
                                       struct multiportswitch_test_mem *self);


#endif

