/* C code generated by lustrec
   SVN version number 1.1-Unversioned directory
   Code is C99 compliant */
   
#ifndef _SELECTOR_PORT_MATRIX_TEST_alloc
#define _SELECTOR_PORT_MATRIX_TEST_alloc

/* Import header from selector_port_matrix_test */
#include "selector_port_matrix_test.h"

/* Import dependencies */

/* Struct definitions */
struct selector_port_matrix_test_mem {struct _arrow_mem *ni_0; };

/* Node allocation function/macro prototypes */
#define selector_port_matrix_test_DECLARE(attr, inst)\
  attr struct selector_port_matrix_test_mem inst;\
  _arrow_DECLARE(attr, inst ## _ni_0);
  
#define selector_port_matrix_test_LINK(inst) do {\
  _arrow_LINK(inst ## _ni_0);\
  inst.ni_0 = &inst ## _ni_0;\
} while (0)

#define selector_port_matrix_test_ALLOC(attr, inst)\
  selector_port_matrix_test_DECLARE(attr, inst);\
  selector_port_matrix_test_LINK(inst);



#endif

