#include <stdio.h>
#include <unistd.h>
#include "/usr/local/include/lustrec/io_frontend.h"
#include <stdlib.h>
#include <assert.h>
#include "selector_port_matrix_test_alloc.h"

/* C code generated by lustrec
   SVN version number 1.1-Unversioned directory
   Code is C99 compliant */
   
int main (int argc, char *argv[]) {
  /* Declaration of inputs/outputs variables */
  double In3_1_1 = 0.;
  double In3_1_2 = 0.;
  double In3_1_3 = 0.;
  double In3_1_4 = 0.;
  double In3_1_5 = 0.;
  double In3_1_6 = 0.;
  double In4_1_1 = 0.;
  double In4_1_2 = 0.;
  double In4_1_3 = 0.;
  double In4_1_4 = 0.;
  double In4_1_5 = 0.;
  double In4_1_6 = 0.;
  double In6_1_1 = 0.;
  double In6_1_2 = 0.;
  double In6_1_3 = 0.;
  double In7_1_1 = 0.;
  double In7_1_2 = 0.;
  double In7_1_3 = 0.;
  double In7_1_4 = 0.;
  double In7_1_5 = 0.;
  double In7_1_6 = 0.;
  double In8_1_1 = 0.;
  double In8_1_2 = 0.;
  double In8_1_3 = 0.;
  double In8_1_4 = 0.;
  double In8_1_5 = 0.;
  double In8_1_6 = 0.;
  double In9_1_1 = 0.;
  double In9_1_2 = 0.;
  double In9_1_3 = 0.;
  double In9_1_4 = 0.;
  double In9_1_5 = 0.;
  double In9_1_6 = 0.;
  double Out2_1_1 = 0.;
  double Out2_1_2 = 0.;
  double Out4_2_1 = 0.;
  double Out4_2_2 = 0.;
  double Out6_3_1 = 0.;
  double Out6_3_2 = 0.;
  double Out7_4_1 = 0.;
  double Out7_4_2 = 0.;
  double Out7_4_3 = 0.;
  double Out8_5_1 = 0.;
  double Out9_6_1 = 0.;
  double Out9_6_2 = 0.;
  double Out9_6_3 = 0.;
  double Out9_6_4 = 0.;
  
  /* Main memory allocation */
  selector_port_matrix_test_ALLOC(static,main_mem);
  
  /* Initialize the main memory */
  selector_port_matrix_test_reset(&main_mem);
  
  ISATTY = isatty(0);
  
  /* Infinite loop */
  while(1){
    fflush(stdout);
    In3_1_1 = _get_double("In3_1_1");
    In3_1_2 = _get_double("In3_1_2");
    In3_1_3 = _get_double("In3_1_3");
    In3_1_4 = _get_double("In3_1_4");
    In3_1_5 = _get_double("In3_1_5");
    In3_1_6 = _get_double("In3_1_6");
    In4_1_1 = _get_double("In4_1_1");
    In4_1_2 = _get_double("In4_1_2");
    In4_1_3 = _get_double("In4_1_3");
    In4_1_4 = _get_double("In4_1_4");
    In4_1_5 = _get_double("In4_1_5");
    In4_1_6 = _get_double("In4_1_6");
    In6_1_1 = _get_double("In6_1_1");
    In6_1_2 = _get_double("In6_1_2");
    In6_1_3 = _get_double("In6_1_3");
    In7_1_1 = _get_double("In7_1_1");
    In7_1_2 = _get_double("In7_1_2");
    In7_1_3 = _get_double("In7_1_3");
    In7_1_4 = _get_double("In7_1_4");
    In7_1_5 = _get_double("In7_1_5");
    In7_1_6 = _get_double("In7_1_6");
    In8_1_1 = _get_double("In8_1_1");
    In8_1_2 = _get_double("In8_1_2");
    In8_1_3 = _get_double("In8_1_3");
    In8_1_4 = _get_double("In8_1_4");
    In8_1_5 = _get_double("In8_1_5");
    In8_1_6 = _get_double("In8_1_6");
    In9_1_1 = _get_double("In9_1_1");
    In9_1_2 = _get_double("In9_1_2");
    In9_1_3 = _get_double("In9_1_3");
    In9_1_4 = _get_double("In9_1_4");
    In9_1_5 = _get_double("In9_1_5");
    In9_1_6 = _get_double("In9_1_6");
    selector_port_matrix_test_step(In3_1_1, In3_1_2, In3_1_3, In3_1_4, In3_1_5, In3_1_6, In4_1_1, In4_1_2, In4_1_3, In4_1_4, In4_1_5, In4_1_6, In6_1_1, In6_1_2, In6_1_3, In7_1_1, In7_1_2, In7_1_3, In7_1_4, In7_1_5, In7_1_6, In8_1_1, In8_1_2, In8_1_3, In8_1_4, In8_1_5, In8_1_6, In9_1_1, In9_1_2, In9_1_3, In9_1_4, In9_1_5, In9_1_6, &Out2_1_1, &Out2_1_2, &Out4_2_1, &Out4_2_2, &Out6_3_1, &Out6_3_2, &Out7_4_1, &Out7_4_2, &Out7_4_3, &Out8_5_1, &Out9_6_1, &Out9_6_2, &Out9_6_3, &Out9_6_4, &main_mem);
    _put_double("Out2_1_1", Out2_1_1);
    _put_double("Out2_1_2", Out2_1_2);
    _put_double("Out4_2_1", Out4_2_1);
    _put_double("Out4_2_2", Out4_2_2);
    _put_double("Out6_3_1", Out6_3_1);
    _put_double("Out6_3_2", Out6_3_2);
    _put_double("Out7_4_1", Out7_4_1);
    _put_double("Out7_4_2", Out7_4_2);
    _put_double("Out7_4_3", Out7_4_3);
    _put_double("Out8_5_1", Out8_5_1);
    _put_double("Out9_6_1", Out9_6_1);
    _put_double("Out9_6_2", Out9_6_2);
    _put_double("Out9_6_3", Out9_6_3);
    _put_double("Out9_6_4", Out9_6_4);
  }
  return 1;
}
