#include <assert.h>
#include "selector_port_matrix_test.h"

/* C code generated by lustrec
   SVN version number 1.1-Unversioned directory
   Code is C99 compliant */
   
/* Import dependencies */

/* Global constants (definitions) */

/* Struct definitions */
struct selector_port_matrix_test_mem {struct _arrow_mem *ni_0; };


void selector_port_matrix_test_reset (struct selector_port_matrix_test_mem *self) {
  
  _arrow_reset(self->ni_0);
  return;
}

void selector_port_matrix_test_step (double In3_1_1, double In3_1_2,
                                     double In3_1_3, double In3_1_4,
                                     double In3_1_5, double In3_1_6,
                                     double In4_1_1, double In4_1_2,
                                     double In4_1_3, double In4_1_4,
                                     double In4_1_5, double In4_1_6,
                                     double In6_1_1, double In6_1_2,
                                     double In6_1_3, double In7_1_1,
                                     double In7_1_2, double In7_1_3,
                                     double In7_1_4, double In7_1_5,
                                     double In7_1_6, double In8_1_1,
                                     double In8_1_2, double In8_1_3,
                                     double In8_1_4, double In8_1_5,
                                     double In8_1_6, double In9_1_1,
                                     double In9_1_2, double In9_1_3,
                                     double In9_1_4, double In9_1_5,
                                     double In9_1_6, 
                                     double (*Out2_1_1), double (*Out2_1_2),
                                     double (*Out4_2_1), double (*Out4_2_2),
                                     double (*Out6_3_1), double (*Out6_3_2),
                                     double (*Out7_4_1), double (*Out7_4_2),
                                     double (*Out7_4_3), double (*Out8_5_1),
                                     double (*Out9_6_1), double (*Out9_6_2),
                                     double (*Out9_6_3), double (*Out9_6_4),
                                     struct selector_port_matrix_test_mem *self) {
  double Selector1_1_1;
  double Selector1_1_2;
  double Selector3_1_1;
  double Selector3_1_2;
  double Selector5_1_1;
  double Selector5_1_2;
  double Selector6_1_1;
  double Selector6_1_2;
  double Selector6_1_3;
  double Selector7_1_1;
  double Selector8_1_1;
  double Selector8_1_2;
  double Selector8_1_3;
  double Selector8_1_4;
  _Bool __selector_port_matrix_test_1;
  int __selector_port_matrix_test_15;
  int __selector_port_matrix_test_2;
  int __selector_port_matrix_test_26;
  int __selector_port_matrix_test_27;
  int __selector_port_matrix_test_3;
  int __selector_port_matrix_test_33;
  _Bool __selector_port_matrix_test_34;
  int __selector_port_matrix_test_35;
  int __selector_port_matrix_test_38;
  int __selector_port_matrix_test_41;
  int __selector_port_matrix_test_43;
  int __selector_port_matrix_test_45;
  int __selector_port_matrix_test_47;
  int __selector_port_matrix_test_9;
  double i_virtual_local;
  
  _arrow_step (1, 0, &__selector_port_matrix_test_1, self->ni_0);
  if (__selector_port_matrix_test_1) {
    i_virtual_local = 0.;
  } else {
    i_virtual_local = 1.;
  }
  Zero_step (1., &__selector_port_matrix_test_9);
  Zero_step (1., &__selector_port_matrix_test_3);
  Zero_step (2., &__selector_port_matrix_test_2);
  Zero_step (2., &__selector_port_matrix_test_47);
  Zero_step (1., &__selector_port_matrix_test_45);
  Zero_step (0., &__selector_port_matrix_test_43);
  Zero_step (1., &__selector_port_matrix_test_41);
  Zero_step (1., &__selector_port_matrix_test_38);
  Zero_step (2., &__selector_port_matrix_test_35);
  Zero_step (1., &__selector_port_matrix_test_33);
  __selector_port_matrix_test_34 = (__selector_port_matrix_test_33 == 0);
  Zero_step (1., &__selector_port_matrix_test_27);
  Zero_step (1., &__selector_port_matrix_test_26);
  Zero_step (0., &__selector_port_matrix_test_15);
  if (((__selector_port_matrix_test_3 == 0) && (__selector_port_matrix_test_2 == 0))) {
    Selector8_1_4 = In9_1_1;
  } else {
    if (((__selector_port_matrix_test_3 == 0) && (__selector_port_matrix_test_2 == 1))) {
      Selector8_1_4 = In9_1_2;
    } else {
      if (((__selector_port_matrix_test_3 == 0) && (__selector_port_matrix_test_2 == 2))) {
        Selector8_1_4 = In9_1_3;
      } else {
        if (((__selector_port_matrix_test_3 == 1) && (__selector_port_matrix_test_2 == 0))) {
          Selector8_1_4 = In9_1_4;
        } else {
          if (((__selector_port_matrix_test_3 == 1) && (__selector_port_matrix_test_2 == 1))) {
            Selector8_1_4 = In9_1_5;
          } else {
            Selector8_1_4 = In9_1_6;
          }
        }
      }
    }
  }
  if (((__selector_port_matrix_test_3 == 0) && (__selector_port_matrix_test_9 == 0))) {
    Selector8_1_3 = In9_1_1;
  } else {
    if (((__selector_port_matrix_test_3 == 0) && (__selector_port_matrix_test_9 == 1))) {
      Selector8_1_3 = In9_1_2;
    } else {
      if (((__selector_port_matrix_test_3 == 0) && (__selector_port_matrix_test_9 == 2))) {
        Selector8_1_3 = In9_1_3;
      } else {
        if (((__selector_port_matrix_test_3 == 1) && (__selector_port_matrix_test_9 == 0))) {
          Selector8_1_3 = In9_1_4;
        } else {
          if (((__selector_port_matrix_test_3 == 1) && (__selector_port_matrix_test_9 == 1))) {
            Selector8_1_3 = In9_1_5;
          } else {
            Selector8_1_3 = In9_1_6;
          }
        }
      }
    }
  }
  if (((__selector_port_matrix_test_15 == 0) && (__selector_port_matrix_test_2 == 0))) {
    Selector8_1_2 = In9_1_1;
  } else {
    if (((__selector_port_matrix_test_15 == 0) && (__selector_port_matrix_test_2 == 1))) {
      Selector8_1_2 = In9_1_2;
    } else {
      if (((__selector_port_matrix_test_15 == 0) && (__selector_port_matrix_test_2 == 2))) {
        Selector8_1_2 = In9_1_3;
      } else {
        if (((__selector_port_matrix_test_15 == 1) && (__selector_port_matrix_test_2 == 0))) {
          Selector8_1_2 = In9_1_4;
        } else {
          if (((__selector_port_matrix_test_15 == 1) && (__selector_port_matrix_test_2 == 1))) {
            Selector8_1_2 = In9_1_5;
          } else {
            Selector8_1_2 = In9_1_6;
          }
        }
      }
    }
  }
  if (((__selector_port_matrix_test_15 == 0) && (__selector_port_matrix_test_9 == 0))) {
    Selector8_1_1 = In9_1_1;
  } else {
    if (((__selector_port_matrix_test_15 == 0) && (__selector_port_matrix_test_9 == 1))) {
      Selector8_1_1 = In9_1_2;
    } else {
      if (((__selector_port_matrix_test_15 == 0) && (__selector_port_matrix_test_9 == 2))) {
        Selector8_1_1 = In9_1_3;
      } else {
        if (((__selector_port_matrix_test_15 == 1) && (__selector_port_matrix_test_9 == 0))) {
          Selector8_1_1 = In9_1_4;
        } else {
          if (((__selector_port_matrix_test_15 == 1) && (__selector_port_matrix_test_9 == 1))) {
            Selector8_1_1 = In9_1_5;
          } else {
            Selector8_1_1 = In9_1_6;
          }
        }
      }
    }
  }
  if (((__selector_port_matrix_test_27 == 1) && (__selector_port_matrix_test_26 == 1))) {
    Selector7_1_1 = In8_1_1;
  } else {
    if (((__selector_port_matrix_test_27 == 1) && (__selector_port_matrix_test_26 == 2))) {
      Selector7_1_1 = In8_1_2;
    } else {
      if (((__selector_port_matrix_test_27 == 1) && (__selector_port_matrix_test_26 == 3))) {
        Selector7_1_1 = In8_1_3;
      } else {
        if (((__selector_port_matrix_test_27 == 2) && (__selector_port_matrix_test_26 == 1))) {
          Selector7_1_1 = In8_1_4;
        } else {
          if (((__selector_port_matrix_test_27 == 2) && (__selector_port_matrix_test_26 == 2))) {
            Selector7_1_1 = In8_1_5;
          } else {
            Selector7_1_1 = In8_1_6;
          }
        }
      }
    }
  }
  if (__selector_port_matrix_test_34) {
    Selector6_1_3 = In7_1_3;
    Selector6_1_2 = In7_1_2;
    Selector6_1_1 = In7_1_1;
  } else {
    Selector6_1_3 = In7_1_6;
    Selector6_1_2 = In7_1_5;
    Selector6_1_1 = In7_1_4;
  }
  if ((__selector_port_matrix_test_35 == 1)) {
    Selector5_1_2 = In6_1_1;
  } else {
    if ((__selector_port_matrix_test_35 == 2)) {
      Selector5_1_2 = In6_1_2;
    } else {
      Selector5_1_2 = In6_1_3;
    }
  }
  if ((__selector_port_matrix_test_38 == 1)) {
    Selector5_1_1 = In6_1_1;
  } else {
    if ((__selector_port_matrix_test_38 == 2)) {
      Selector5_1_1 = In6_1_2;
    } else {
      Selector5_1_1 = In6_1_3;
    }
  }
  if ((__selector_port_matrix_test_41 == 0)) {
    Selector3_1_2 = In4_1_2;
  } else {
    Selector3_1_2 = In4_1_5;
  }
  if ((__selector_port_matrix_test_43 == 0)) {
    Selector3_1_1 = In4_1_2;
  } else {
    Selector3_1_1 = In4_1_5;
  }
  if ((__selector_port_matrix_test_45 == 1)) {
    Selector1_1_2 = In3_1_1;
  } else {
    Selector1_1_2 = In3_1_4;
  }
  if ((__selector_port_matrix_test_47 == 1)) {
    Selector1_1_1 = In3_1_1;
  } else {
    Selector1_1_1 = In3_1_4;
  }
  *Out9_6_4 = Selector8_1_4;
  *Out9_6_3 = Selector8_1_3;
  *Out9_6_2 = Selector8_1_2;
  *Out9_6_1 = Selector8_1_1;
  *Out8_5_1 = Selector7_1_1;
  *Out7_4_3 = Selector6_1_3;
  *Out7_4_2 = Selector6_1_2;
  *Out7_4_1 = Selector6_1_1;
  *Out6_3_2 = Selector5_1_2;
  *Out6_3_1 = Selector5_1_1;
  *Out4_2_2 = Selector3_1_2;
  *Out4_2_1 = Selector3_1_1;
  *Out2_1_2 = Selector1_1_2;
  *Out2_1_1 = Selector1_1_1;
  return;
}

void Zero_step (double In, 
                int (*Out)
                ) {
  
  *Out = 0;
  return;
}

