#include <stdio.h>
#include <unistd.h>
#include "/usr/local/include/lustrec/io_frontend.h"
#include <stdlib.h>
#include <assert.h>
#include "dss_test_alloc.h"

/* C code generated by lustrec
   SVN version number 1.1-Unversioned directory
   Code is C99 compliant */
   
int main (int argc, char *argv[]) {
  /* Declaration of inputs/outputs variables */
  double In1_1_1 = 0.;
  double In2_1_1 = 0.;
  double In3_1_1 = 0.;
  double In4_1_1 = 0.;
  double In4_1_2 = 0.;
  double In5_1_1 = 0.;
  double In5_1_2 = 0.;
  double In6_1_1 = 0.;
  double In6_1_2 = 0.;
  double In7_1_1 = 0.;
  double Out1_1_1 = 0.;
  double Out2_2_1 = 0.;
  double Out3_3_1 = 0.;
  double Out4_4_1 = 0.;
  double Out4_4_2 = 0.;
  double Out5_5_1 = 0.;
  double Out5_5_2 = 0.;
  double Out6_6_1 = 0.;
  double Out6_6_2 = 0.;
  double Out7_7_1 = 0.;
  
  /* Main memory allocation */
  dss_test_ALLOC(static,main_mem);
  
  /* Initialize the main memory */
  dss_test_reset(&main_mem);
  
  ISATTY = isatty(0);
  
  /* Infinite loop */
  while(1){
    fflush(stdout);
    In1_1_1 = _get_double("In1_1_1");
    In2_1_1 = _get_double("In2_1_1");
    In3_1_1 = _get_double("In3_1_1");
    In4_1_1 = _get_double("In4_1_1");
    In4_1_2 = _get_double("In4_1_2");
    In5_1_1 = _get_double("In5_1_1");
    In5_1_2 = _get_double("In5_1_2");
    In6_1_1 = _get_double("In6_1_1");
    In6_1_2 = _get_double("In6_1_2");
    In7_1_1 = _get_double("In7_1_1");
    dss_test_step(In1_1_1, In2_1_1, In3_1_1, In4_1_1, In4_1_2, In5_1_1, In5_1_2, In6_1_1, In6_1_2, In7_1_1, &Out1_1_1, &Out2_2_1, &Out3_3_1, &Out4_4_1, &Out4_4_2, &Out5_5_1, &Out5_5_2, &Out6_6_1, &Out6_6_2, &Out7_7_1, &main_mem);
    _put_double("Out1_1_1", Out1_1_1);
    _put_double("Out2_2_1", Out2_2_1);
    _put_double("Out3_3_1", Out3_3_1);
    _put_double("Out4_4_1", Out4_4_1);
    _put_double("Out4_4_2", Out4_4_2);
    _put_double("Out5_5_1", Out5_5_1);
    _put_double("Out5_5_2", Out5_5_2);
    _put_double("Out6_6_1", Out6_6_1);
    _put_double("Out6_6_2", Out6_6_2);
    _put_double("Out7_7_1", Out7_7_1);
  }
  return 1;
}
