/* C code generated by lustrec
   SVN version number 1.1-Unversioned directory
   Code is C99 compliant */
   
#ifndef _DSS_TEST
#define _DSS_TEST

/* Imports standard library */
#include "/usr/local/include/lustrec/arrow.h"


/* Import dependencies */

/* Types definitions */

/* Global constant (declarations, definitions are in C file) */

/* Struct declarations */
struct dss_test_mem;

/* Nodes declarations */
extern void dss_test_reset (struct dss_test_mem *self);

extern void dss_test_step (double In1_1_1, double In2_1_1, double In3_1_1,
                           double In4_1_1, double In4_1_2, double In5_1_1,
                           double In5_1_2, double In6_1_1, double In6_1_2,
                           double In7_1_1, 
                           double (*Out1_1_1), double (*Out2_2_1),
                           double (*Out3_3_1), double (*Out4_4_1),
                           double (*Out4_4_2), double (*Out5_5_1),
                           double (*Out5_5_2), double (*Out6_6_1),
                           double (*Out6_6_2), double (*Out7_7_1),
                           struct dss_test_mem *self);


#endif

