/* C code generated by lustrec
   SVN version number 1.1-Unversioned directory
   Code is C99 compliant */
   
#ifndef _DSS_TEST_alloc
#define _DSS_TEST_alloc

/* Import header from dss_test */
#include "dss_test.h"

/* Import dependencies */

/* Struct definitions */
struct dss_test_mem {struct dss_test_reg {double __dss_test_10; double __dss_test_11; double __dss_test_12; double __dss_test_13; double __dss_test_14; double __dss_test_15; double __dss_test_16; double __dss_test_17; double __dss_test_18; double __dss_test_19; double __dss_test_2; double __dss_test_20; double __dss_test_21; double __dss_test_3; double __dss_test_4; double __dss_test_5; double __dss_test_6; double __dss_test_7; double __dss_test_8; double __dss_test_9; } _reg; struct _arrow_mem *ni_0; };

/* Node allocation function/macro prototypes */
#define dss_test_DECLARE(attr, inst)\
  attr struct dss_test_mem inst;\
  _arrow_DECLARE(attr, inst ## _ni_0);
  
#define dss_test_LINK(inst) do {\
  _arrow_LINK(inst ## _ni_0);\
  inst.ni_0 = &inst ## _ni_0;\
} while (0)

#define dss_test_ALLOC(attr, inst)\
  dss_test_DECLARE(attr, inst);\
  dss_test_LINK(inst);



#endif

