#include <assert.h>
#include "dss_test.h"

/* C code generated by lustrec
   SVN version number 1.1-Unversioned directory
   Code is C99 compliant */
   
/* Import dependencies */

/* Global constants (definitions) */

/* Struct definitions */
struct dss_test_mem {struct dss_test_reg {double __dss_test_10; double __dss_test_11; double __dss_test_12; double __dss_test_13; double __dss_test_14; double __dss_test_15; double __dss_test_16; double __dss_test_17; double __dss_test_18; double __dss_test_19; double __dss_test_2; double __dss_test_20; double __dss_test_21; double __dss_test_3; double __dss_test_4; double __dss_test_5; double __dss_test_6; double __dss_test_7; double __dss_test_8; double __dss_test_9; } _reg; struct _arrow_mem *ni_0; };


void dss_test_reset (struct dss_test_mem *self) {
  
  _arrow_reset(self->ni_0);
  return;
}

void dss_test_step (double In1_1_1, double In2_1_1, double In3_1_1,
                    double In4_1_1, double In4_1_2, double In5_1_1,
                    double In5_1_2, double In6_1_1, double In6_1_2,
                    double In7_1_1, 
                    double (*Out1_1_1), double (*Out2_2_1),
                    double (*Out3_3_1), double (*Out4_4_1),
                    double (*Out4_4_2), double (*Out5_5_1),
                    double (*Out5_5_2), double (*Out6_6_1),
                    double (*Out6_6_2), double (*Out7_7_1),
                    struct dss_test_mem *self) {
  double DiscreteStateSpace3_tmp_1;
  double DiscreteStateSpace3_tmp_2;
  double DiscreteStateSpace3_tmp_3;
  double DiscreteStateSpace4_tmp_1;
  double DiscreteStateSpace4_tmp_2;
  double DiscreteStateSpace4_tmp_3;
  double DiscreteStateSpace5_tmp_1;
  double DiscreteStateSpace5_tmp_2;
  double DiscreteStateSpace5_tmp_3;
  double DiscreteStateSpace6_tmp_1;
  double DiscreteStateSpace6_tmp_2;
  double DiscreteStateSpace_tmp_1;
  _Bool __dss_test_1;
  double i_virtual_local;
  
  _arrow_step (1, 0, &__dss_test_1, self->ni_0);
  if (__dss_test_1) {
    i_virtual_local = 0.;
    DiscreteStateSpace5_tmp_3 = (- 3.);
    DiscreteStateSpace5_tmp_2 = (- 2.);
    DiscreteStateSpace5_tmp_1 = (- 1.);
  } else {
    i_virtual_local = 1.;
    DiscreteStateSpace5_tmp_3 = ((((7. * self->_reg.__dss_test_9) + (8. * self->_reg.__dss_test_8)) + (9. * self->_reg.__dss_test_7)) + ((14. * self->_reg.__dss_test_6) + (15. * self->_reg.__dss_test_5)));
    DiscreteStateSpace5_tmp_2 = ((((4. * self->_reg.__dss_test_9) + (5. * self->_reg.__dss_test_8)) + (6. * self->_reg.__dss_test_7)) + ((12. * self->_reg.__dss_test_6) + (13. * self->_reg.__dss_test_5)));
    DiscreteStateSpace5_tmp_1 = (((self->_reg.__dss_test_9 + (2. * self->_reg.__dss_test_8)) + (3. * self->_reg.__dss_test_7)) + ((10. * self->_reg.__dss_test_6) + (11. * self->_reg.__dss_test_5)));
  }
  self->_reg.__dss_test_9 = DiscreteStateSpace5_tmp_1;
  self->_reg.__dss_test_8 = DiscreteStateSpace5_tmp_2;
  self->_reg.__dss_test_7 = DiscreteStateSpace5_tmp_3;
  self->_reg.__dss_test_6 = In6_1_1;
  self->_reg.__dss_test_5 = In6_1_2;
  if (__dss_test_1) {
    DiscreteStateSpace6_tmp_2 = (- 25.);
    DiscreteStateSpace6_tmp_1 = (- 25.);
  } else {
    DiscreteStateSpace6_tmp_2 = (((3. * self->_reg.__dss_test_4) + (4. * self->_reg.__dss_test_3)) + (6. * self->_reg.__dss_test_2));
    DiscreteStateSpace6_tmp_1 = ((self->_reg.__dss_test_4 + (2. * self->_reg.__dss_test_3)) + (5. * self->_reg.__dss_test_2));
  }
  self->_reg.__dss_test_4 = DiscreteStateSpace6_tmp_1;
  self->_reg.__dss_test_3 = DiscreteStateSpace6_tmp_2;
  if (__dss_test_1) {
    DiscreteStateSpace_tmp_1 = 0.;
  } else {
    DiscreteStateSpace_tmp_1 = (self->_reg.__dss_test_21 + self->_reg.__dss_test_20);
  }
  self->_reg.__dss_test_21 = DiscreteStateSpace_tmp_1;
  self->_reg.__dss_test_20 = In1_1_1;
  self->_reg.__dss_test_2 = In7_1_1;
  if (__dss_test_1) {
    DiscreteStateSpace3_tmp_3 = 0.;
    DiscreteStateSpace3_tmp_2 = 0.;
    DiscreteStateSpace3_tmp_1 = 0.;
  } else {
    DiscreteStateSpace3_tmp_3 = ((((7. * self->_reg.__dss_test_19) + (8. * self->_reg.__dss_test_18)) + (9. * self->_reg.__dss_test_17)) + ((14. * self->_reg.__dss_test_16) + (15. * self->_reg.__dss_test_15)));
    DiscreteStateSpace3_tmp_2 = ((((4. * self->_reg.__dss_test_19) + (5. * self->_reg.__dss_test_18)) + (6. * self->_reg.__dss_test_17)) + ((12. * self->_reg.__dss_test_16) + (13. * self->_reg.__dss_test_15)));
    DiscreteStateSpace3_tmp_1 = (((self->_reg.__dss_test_19 + (2. * self->_reg.__dss_test_18)) + (3. * self->_reg.__dss_test_17)) + ((10. * self->_reg.__dss_test_16) + (11. * self->_reg.__dss_test_15)));
  }
  self->_reg.__dss_test_19 = DiscreteStateSpace3_tmp_1;
  self->_reg.__dss_test_18 = DiscreteStateSpace3_tmp_2;
  self->_reg.__dss_test_17 = DiscreteStateSpace3_tmp_3;
  self->_reg.__dss_test_16 = In4_1_1;
  self->_reg.__dss_test_15 = In4_1_2;
  if (__dss_test_1) {
    DiscreteStateSpace4_tmp_3 = (- 1.);
    DiscreteStateSpace4_tmp_2 = (- 1.);
    DiscreteStateSpace4_tmp_1 = (- 1.);
  } else {
    DiscreteStateSpace4_tmp_3 = ((((7. * self->_reg.__dss_test_14) + (8. * self->_reg.__dss_test_13)) + (9. * self->_reg.__dss_test_12)) + ((14. * self->_reg.__dss_test_11) + (15. * self->_reg.__dss_test_10)));
    DiscreteStateSpace4_tmp_2 = ((((4. * self->_reg.__dss_test_14) + (5. * self->_reg.__dss_test_13)) + (6. * self->_reg.__dss_test_12)) + ((12. * self->_reg.__dss_test_11) + (13. * self->_reg.__dss_test_10)));
    DiscreteStateSpace4_tmp_1 = (((self->_reg.__dss_test_14 + (2. * self->_reg.__dss_test_13)) + (3. * self->_reg.__dss_test_12)) + ((10. * self->_reg.__dss_test_11) + (11. * self->_reg.__dss_test_10)));
  }
  self->_reg.__dss_test_14 = DiscreteStateSpace4_tmp_1;
  self->_reg.__dss_test_13 = DiscreteStateSpace4_tmp_2;
  self->_reg.__dss_test_12 = DiscreteStateSpace4_tmp_3;
  self->_reg.__dss_test_11 = In5_1_1;
  self->_reg.__dss_test_10 = In5_1_2;
  *Out7_7_1 = (((7. * DiscreteStateSpace6_tmp_1) + (8. * DiscreteStateSpace6_tmp_2)) + (9. * In7_1_1));
  *Out6_6_2 = ((((19. * DiscreteStateSpace5_tmp_1) + (20. * DiscreteStateSpace5_tmp_2)) + (21. * DiscreteStateSpace5_tmp_3)) + ((24. * In6_1_1) + (25. * In6_1_2)));
  *Out6_6_1 = ((((16. * DiscreteStateSpace5_tmp_1) + (17. * DiscreteStateSpace5_tmp_2)) + (18. * DiscreteStateSpace5_tmp_3)) + ((22. * In6_1_1) + (23. * In6_1_2)));
  *Out5_5_2 = ((((19. * DiscreteStateSpace4_tmp_1) + (20. * DiscreteStateSpace4_tmp_2)) + (21. * DiscreteStateSpace4_tmp_3)) + ((24. * In5_1_1) + (25. * In5_1_2)));
  *Out5_5_1 = ((((16. * DiscreteStateSpace4_tmp_1) + (17. * DiscreteStateSpace4_tmp_2)) + (18. * DiscreteStateSpace4_tmp_3)) + ((22. * In5_1_1) + (23. * In5_1_2)));
  *Out4_4_2 = ((((19. * DiscreteStateSpace3_tmp_1) + (20. * DiscreteStateSpace3_tmp_2)) + (21. * DiscreteStateSpace3_tmp_3)) + ((24. * In4_1_1) + (25. * In4_1_2)));
  *Out4_4_1 = ((((16. * DiscreteStateSpace3_tmp_1) + (17. * DiscreteStateSpace3_tmp_2)) + (18. * DiscreteStateSpace3_tmp_3)) + ((22. * In4_1_1) + (23. * In4_1_2)));
  *Out3_3_1 = In3_1_1;
  *Out2_2_1 = In2_1_1;
  *Out1_1_1 = (DiscreteStateSpace_tmp_1 + In1_1_1);
  return;
}

