#include <stdio.h>
#include <unistd.h>
#include "/usr/local/include/lustrec/io_frontend.h"
#include <stdlib.h>
#include <assert.h>
#include "product_collapse_test_alloc.h"

/* C code generated by lustrec
   SVN version number 1.1-Unversioned directory
   Code is C99 compliant */
   
int main (int argc, char *argv[]) {
  /* Declaration of inputs/outputs variables */
  double In1_1_1 = 0.;
  double In3_1_1 = 0.;
  double In3_1_2 = 0.;
  double In3_1_3 = 0.;
  double In3_1_4 = 0.;
  double In3_1_5 = 0.;
  double In3_1_6 = 0.;
  double In2_1_1 = 0.;
  double In2_1_2 = 0.;
  double In2_1_3 = 0.;
  double In7_1_1 = 0.;
  double In8_1_1 = 0.;
  double In8_1_2 = 0.;
  double In8_1_3 = 0.;
  double In9_1_1 = 0.;
  double In9_1_2 = 0.;
  double In9_1_3 = 0.;
  double In9_1_4 = 0.;
  double In9_1_5 = 0.;
  double In9_1_6 = 0.;
  double In4_1_1 = 0.;
  double In6_1_1 = 0.;
  double In6_1_2 = 0.;
  double In6_1_3 = 0.;
  double In6_1_4 = 0.;
  double In6_1_5 = 0.;
  double In6_1_6 = 0.;
  double In5_1_1 = 0.;
  double In5_1_2 = 0.;
  double In5_1_3 = 0.;
  double In10_1_1 = 0.;
  double In10_1_2 = 0.;
  double In10_1_3 = 0.;
  double In10_1_4 = 0.;
  double In10_1_5 = 0.;
  double In10_1_6 = 0.;
  double In11_1_1 = 0.;
  double In12_1_1 = 0.;
  double In12_1_2 = 0.;
  double In12_1_3 = 0.;
  double In13_1_1 = 0.;
  double In13_1_2 = 0.;
  double In13_1_3 = 0.;
  double In13_1_4 = 0.;
  double In13_1_5 = 0.;
  double In13_1_6 = 0.;
  double In14_1_1 = 0.;
  double In14_1_2 = 0.;
  double In14_1_3 = 0.;
  double In14_1_4 = 0.;
  double In14_1_5 = 0.;
  double In14_1_6 = 0.;
  double Out1_1_1 = 0.;
  double Out3_2_1 = 0.;
  double Out2_3_1 = 0.;
  double Out7_4_1 = 0.;
  double Out8_5_1 = 0.;
  double Out9_6_1 = 0.;
  double Out9_6_2 = 0.;
  double Out9_6_3 = 0.;
  double Out4_7_1 = 0.;
  double Out6_8_1 = 0.;
  double Out5_9_1 = 0.;
  double Out10_10_1 = 0.;
  double Out10_10_2 = 0.;
  double Out11_11_1 = 0.;
  double Out12_12_1 = 0.;
  double Out13_13_1 = 0.;
  double Out13_13_2 = 0.;
  double Out13_13_3 = 0.;
  double Out14_14_1 = 0.;
  double Out14_14_2 = 0.;
  
  /* Main memory allocation */
  product_collapse_test_ALLOC(static,main_mem);
  
  /* Initialize the main memory */
  product_collapse_test_reset(&main_mem);
  
  ISATTY = isatty(0);
  
  /* Infinite loop */
  while(1){
    fflush(stdout);
    In1_1_1 = _get_double("In1_1_1");
    In3_1_1 = _get_double("In3_1_1");
    In3_1_2 = _get_double("In3_1_2");
    In3_1_3 = _get_double("In3_1_3");
    In3_1_4 = _get_double("In3_1_4");
    In3_1_5 = _get_double("In3_1_5");
    In3_1_6 = _get_double("In3_1_6");
    In2_1_1 = _get_double("In2_1_1");
    In2_1_2 = _get_double("In2_1_2");
    In2_1_3 = _get_double("In2_1_3");
    In7_1_1 = _get_double("In7_1_1");
    In8_1_1 = _get_double("In8_1_1");
    In8_1_2 = _get_double("In8_1_2");
    In8_1_3 = _get_double("In8_1_3");
    In9_1_1 = _get_double("In9_1_1");
    In9_1_2 = _get_double("In9_1_2");
    In9_1_3 = _get_double("In9_1_3");
    In9_1_4 = _get_double("In9_1_4");
    In9_1_5 = _get_double("In9_1_5");
    In9_1_6 = _get_double("In9_1_6");
    In4_1_1 = _get_double("In4_1_1");
    In6_1_1 = _get_double("In6_1_1");
    In6_1_2 = _get_double("In6_1_2");
    In6_1_3 = _get_double("In6_1_3");
    In6_1_4 = _get_double("In6_1_4");
    In6_1_5 = _get_double("In6_1_5");
    In6_1_6 = _get_double("In6_1_6");
    In5_1_1 = _get_double("In5_1_1");
    In5_1_2 = _get_double("In5_1_2");
    In5_1_3 = _get_double("In5_1_3");
    In10_1_1 = _get_double("In10_1_1");
    In10_1_2 = _get_double("In10_1_2");
    In10_1_3 = _get_double("In10_1_3");
    In10_1_4 = _get_double("In10_1_4");
    In10_1_5 = _get_double("In10_1_5");
    In10_1_6 = _get_double("In10_1_6");
    In11_1_1 = _get_double("In11_1_1");
    In12_1_1 = _get_double("In12_1_1");
    In12_1_2 = _get_double("In12_1_2");
    In12_1_3 = _get_double("In12_1_3");
    In13_1_1 = _get_double("In13_1_1");
    In13_1_2 = _get_double("In13_1_2");
    In13_1_3 = _get_double("In13_1_3");
    In13_1_4 = _get_double("In13_1_4");
    In13_1_5 = _get_double("In13_1_5");
    In13_1_6 = _get_double("In13_1_6");
    In14_1_1 = _get_double("In14_1_1");
    In14_1_2 = _get_double("In14_1_2");
    In14_1_3 = _get_double("In14_1_3");
    In14_1_4 = _get_double("In14_1_4");
    In14_1_5 = _get_double("In14_1_5");
    In14_1_6 = _get_double("In14_1_6");
    product_collapse_test_step(In1_1_1, In3_1_1, In3_1_2, In3_1_3, In3_1_4, In3_1_5, In3_1_6, In2_1_1, In2_1_2, In2_1_3, In7_1_1, In8_1_1, In8_1_2, In8_1_3, In9_1_1, In9_1_2, In9_1_3, In9_1_4, In9_1_5, In9_1_6, In4_1_1, In6_1_1, In6_1_2, In6_1_3, In6_1_4, In6_1_5, In6_1_6, In5_1_1, In5_1_2, In5_1_3, In10_1_1, In10_1_2, In10_1_3, In10_1_4, In10_1_5, In10_1_6, In11_1_1, In12_1_1, In12_1_2, In12_1_3, In13_1_1, In13_1_2, In13_1_3, In13_1_4, In13_1_5, In13_1_6, In14_1_1, In14_1_2, In14_1_3, In14_1_4, In14_1_5, In14_1_6, &Out1_1_1, &Out3_2_1, &Out2_3_1, &Out7_4_1, &Out8_5_1, &Out9_6_1, &Out9_6_2, &Out9_6_3, &Out4_7_1, &Out6_8_1, &Out5_9_1, &Out10_10_1, &Out10_10_2, &Out11_11_1, &Out12_12_1, &Out13_13_1, &Out13_13_2, &Out13_13_3, &Out14_14_1, &Out14_14_2, &main_mem);
    _put_double("Out1_1_1", Out1_1_1);
    _put_double("Out3_2_1", Out3_2_1);
    _put_double("Out2_3_1", Out2_3_1);
    _put_double("Out7_4_1", Out7_4_1);
    _put_double("Out8_5_1", Out8_5_1);
    _put_double("Out9_6_1", Out9_6_1);
    _put_double("Out9_6_2", Out9_6_2);
    _put_double("Out9_6_3", Out9_6_3);
    _put_double("Out4_7_1", Out4_7_1);
    _put_double("Out6_8_1", Out6_8_1);
    _put_double("Out5_9_1", Out5_9_1);
    _put_double("Out10_10_1", Out10_10_1);
    _put_double("Out10_10_2", Out10_10_2);
    _put_double("Out11_11_1", Out11_11_1);
    _put_double("Out12_12_1", Out12_12_1);
    _put_double("Out13_13_1", Out13_13_1);
    _put_double("Out13_13_2", Out13_13_2);
    _put_double("Out13_13_3", Out13_13_3);
    _put_double("Out14_14_1", Out14_14_1);
    _put_double("Out14_14_2", Out14_14_2);
  }
  return 1;
}
