/* C code generated by lustrec
   SVN version number 1.1-Unversioned directory
   Code is C99 compliant */
   
#ifndef _PRODUCT_COLLAPSE_TEST
#define _PRODUCT_COLLAPSE_TEST

/* Imports standard library */
#include "/usr/local/include/lustrec/arrow.h"


/* Import dependencies */

/* Types definitions */

/* Global constant (declarations, definitions are in C file) */

/* Struct declarations */
struct product_collapse_test_mem;

/* Nodes declarations */
extern void product_collapse_test_reset (struct product_collapse_test_mem *self);

extern void product_collapse_test_step (double In1_1_1, double In3_1_1,
                                        double In3_1_2, double In3_1_3,
                                        double In3_1_4, double In3_1_5,
                                        double In3_1_6, double In2_1_1,
                                        double In2_1_2, double In2_1_3,
                                        double In7_1_1, double In8_1_1,
                                        double In8_1_2, double In8_1_3,
                                        double In9_1_1, double In9_1_2,
                                        double In9_1_3, double In9_1_4,
                                        double In9_1_5, double In9_1_6,
                                        double In4_1_1, double In6_1_1,
                                        double In6_1_2, double In6_1_3,
                                        double In6_1_4, double In6_1_5,
                                        double In6_1_6, double In5_1_1,
                                        double In5_1_2, double In5_1_3,
                                        double In10_1_1, double In10_1_2,
                                        double In10_1_3, double In10_1_4,
                                        double In10_1_5, double In10_1_6,
                                        double In11_1_1, double In12_1_1,
                                        double In12_1_2, double In12_1_3,
                                        double In13_1_1, double In13_1_2,
                                        double In13_1_3, double In13_1_4,
                                        double In13_1_5, double In13_1_6,
                                        double In14_1_1, double In14_1_2,
                                        double In14_1_3, double In14_1_4,
                                        double In14_1_5, double In14_1_6, 
                                        double (*Out1_1_1),
                                        double (*Out3_2_1),
                                        double (*Out2_3_1),
                                        double (*Out7_4_1),
                                        double (*Out8_5_1),
                                        double (*Out9_6_1),
                                        double (*Out9_6_2),
                                        double (*Out9_6_3),
                                        double (*Out4_7_1),
                                        double (*Out6_8_1),
                                        double (*Out5_9_1),
                                        double (*Out10_10_1),
                                        double (*Out10_10_2),
                                        double (*Out11_11_1),
                                        double (*Out12_12_1),
                                        double (*Out13_13_1),
                                        double (*Out13_13_2),
                                        double (*Out13_13_3),
                                        double (*Out14_14_1),
                                        double (*Out14_14_2),
                                        struct product_collapse_test_mem *self);


#endif

