/* C code generated by lustrec
   SVN version number 1.1-Unversioned directory
   Code is C99 compliant */
   
#ifndef _PRODUCT_COLLAPSE_TEST_alloc
#define _PRODUCT_COLLAPSE_TEST_alloc

/* Import header from product_collapse_test */
#include "product_collapse_test.h"

/* Import dependencies */

/* Struct definitions */
struct product_collapse_test_mem {struct _arrow_mem *ni_0; };

/* Node allocation function/macro prototypes */
#define product_collapse_test_DECLARE(attr, inst)\
  attr struct product_collapse_test_mem inst;\
  _arrow_DECLARE(attr, inst ## _ni_0);
  
#define product_collapse_test_LINK(inst) do {\
  _arrow_LINK(inst ## _ni_0);\
  inst.ni_0 = &inst ## _ni_0;\
} while (0)

#define product_collapse_test_ALLOC(attr, inst)\
  product_collapse_test_DECLARE(attr, inst);\
  product_collapse_test_LINK(inst);



#endif

