#include <assert.h>
#include "product_collapse_test.h"

/* C code generated by lustrec
   SVN version number 1.1-Unversioned directory
   Code is C99 compliant */
   
/* Import dependencies */

/* Global constants (definitions) */

/* Struct definitions */
struct product_collapse_test_mem {struct _arrow_mem *ni_0; };


void product_collapse_test_reset (struct product_collapse_test_mem *self) {
  
  _arrow_reset(self->ni_0);
  return;
}

void product_collapse_test_step (double In1_1_1, double In3_1_1,
                                 double In3_1_2, double In3_1_3,
                                 double In3_1_4, double In3_1_5,
                                 double In3_1_6, double In2_1_1,
                                 double In2_1_2, double In2_1_3,
                                 double In7_1_1, double In8_1_1,
                                 double In8_1_2, double In8_1_3,
                                 double In9_1_1, double In9_1_2,
                                 double In9_1_3, double In9_1_4,
                                 double In9_1_5, double In9_1_6,
                                 double In4_1_1, double In6_1_1,
                                 double In6_1_2, double In6_1_3,
                                 double In6_1_4, double In6_1_5,
                                 double In6_1_6, double In5_1_1,
                                 double In5_1_2, double In5_1_3,
                                 double In10_1_1, double In10_1_2,
                                 double In10_1_3, double In10_1_4,
                                 double In10_1_5, double In10_1_6,
                                 double In11_1_1, double In12_1_1,
                                 double In12_1_2, double In12_1_3,
                                 double In13_1_1, double In13_1_2,
                                 double In13_1_3, double In13_1_4,
                                 double In13_1_5, double In13_1_6,
                                 double In14_1_1, double In14_1_2,
                                 double In14_1_3, double In14_1_4,
                                 double In14_1_5, double In14_1_6, 
                                 double (*Out1_1_1), double (*Out3_2_1),
                                 double (*Out2_3_1), double (*Out7_4_1),
                                 double (*Out8_5_1), double (*Out9_6_1),
                                 double (*Out9_6_2), double (*Out9_6_3),
                                 double (*Out4_7_1), double (*Out6_8_1),
                                 double (*Out5_9_1), double (*Out10_10_1),
                                 double (*Out10_10_2), double (*Out11_11_1),
                                 double (*Out12_12_1), double (*Out13_13_1),
                                 double (*Out13_13_2), double (*Out13_13_3),
                                 double (*Out14_14_1), double (*Out14_14_2),
                                 struct product_collapse_test_mem *self) {
  _Bool __product_collapse_test_1;
  double i_virtual_local;
  
  _arrow_step (1, 0, &__product_collapse_test_1, self->ni_0);
  if (__product_collapse_test_1) {
    i_virtual_local = 0.;
  } else {
    i_virtual_local = 1.;
  }
  *Out9_6_3 = (In9_1_3 * In9_1_6);
  *Out9_6_2 = (In9_1_2 * In9_1_5);
  *Out9_6_1 = (In9_1_1 * In9_1_4);
  *Out8_5_1 = ((In8_1_1 * In8_1_2) * In8_1_3);
  *Out7_4_1 = In7_1_1;
  *Out6_8_1 = ((((((1. / In6_1_1) * (1. / In6_1_2)) * (1. / In6_1_3)) * (1. / In6_1_4)) * (1. / In6_1_5)) * (1. / In6_1_6));
  *Out5_9_1 = (((1. / In5_1_1) * (1. / In5_1_2)) * (1. / In5_1_3));
  *Out4_7_1 = (1. / In4_1_1);
  *Out3_2_1 = (((((In3_1_1 * In3_1_2) * In3_1_3) * In3_1_4) * In3_1_5) * In3_1_6);
  *Out2_3_1 = ((In2_1_1 * In2_1_2) * In2_1_3);
  *Out1_1_1 = In1_1_1;
  *Out14_14_2 = (((1. / In14_1_4) * (1. / In14_1_5)) * (1. / In14_1_6));
  *Out14_14_1 = (((1. / In14_1_1) * (1. / In14_1_2)) * (1. / In14_1_3));
  *Out13_13_3 = ((1. / In13_1_3) * (1. / In13_1_6));
  *Out13_13_2 = ((1. / In13_1_2) * (1. / In13_1_5));
  *Out13_13_1 = ((1. / In13_1_1) * (1. / In13_1_4));
  *Out12_12_1 = (((1. / In12_1_1) * (1. / In12_1_2)) * (1. / In12_1_3));
  *Out11_11_1 = (1. / In11_1_1);
  *Out10_10_2 = ((In10_1_4 * In10_1_5) * In10_1_6);
  *Out10_10_1 = ((In10_1_1 * In10_1_2) * In10_1_3);
  return;
}

