/* C code generated by lustrec
   SVN version number 1.1-Unversioned directory
   Code is C99 compliant */
   
#ifndef _MULTIPORTSWITCH_VECT_TEST
#define _MULTIPORTSWITCH_VECT_TEST

/* Imports standard library */
#include "/usr/local/include/lustrec/arrow.h"


/* Import dependencies */

/* Types definitions */

/* Global constant (declarations, definitions are in C file) */

/* Struct declarations */
struct multiportswitch_vect_test_mem;

/* Nodes declarations */
extern void multiportswitch_vect_test_reset (struct multiportswitch_vect_test_mem *self);

extern void multiportswitch_vect_test_step (double In5_1_1, double In5_1_2,
                                            double In5_1_3, double In5_1_4,
                                            double In5_1_5, int In8_1_1,
                                            double In9_1_1, double In17_1_1,
                                            double In17_1_2, double In17_1_3,
                                            double In17_1_4, double In17_1_5,
                                            double In17_1_6, double In17_1_7,
                                            double In17_1_8, double In17_1_9,
                                            int In20_1_1, double In21_1_1,
                                            double In21_1_2, double In21_1_3,
                                            double In21_1_4, 
                                            double (*Out2_1_1),
                                            double (*Out3_2_1),
                                            double (*Out5_3_1),
                                            double (*Out6_4_1),
                                            struct multiportswitch_vect_test_mem *self);


#endif

