#include <stdio.h>
#include <unistd.h>
#include "/usr/local/include/lustrec/io_frontend.h"
#include <stdlib.h>
#include <assert.h>
#include "multiportswitch_vect_test_alloc.h"

/* C code generated by lustrec
   SVN version number 1.1-Unversioned directory
   Code is C99 compliant */
   
int main (int argc, char *argv[]) {
  /* Declaration of inputs/outputs variables */
  double In5_1_1 = 0.;
  double In5_1_2 = 0.;
  double In5_1_3 = 0.;
  double In5_1_4 = 0.;
  double In5_1_5 = 0.;
  int In8_1_1 = 0;
  double In9_1_1 = 0.;
  double In17_1_1 = 0.;
  double In17_1_2 = 0.;
  double In17_1_3 = 0.;
  double In17_1_4 = 0.;
  double In17_1_5 = 0.;
  double In17_1_6 = 0.;
  double In17_1_7 = 0.;
  double In17_1_8 = 0.;
  double In17_1_9 = 0.;
  int In20_1_1 = 0;
  double In21_1_1 = 0.;
  double In21_1_2 = 0.;
  double In21_1_3 = 0.;
  double In21_1_4 = 0.;
  double Out2_1_1 = 0.;
  double Out3_2_1 = 0.;
  double Out5_3_1 = 0.;
  double Out6_4_1 = 0.;
  
  /* Main memory allocation */
  multiportswitch_vect_test_ALLOC(static,main_mem);
  
  /* Initialize the main memory */
  multiportswitch_vect_test_reset(&main_mem);
  
  ISATTY = isatty(0);
  
  /* Infinite loop */
  while(1){
    fflush(stdout);
    In5_1_1 = _get_double("In5_1_1");
    In5_1_2 = _get_double("In5_1_2");
    In5_1_3 = _get_double("In5_1_3");
    In5_1_4 = _get_double("In5_1_4");
    In5_1_5 = _get_double("In5_1_5");
    In8_1_1 = _get_int("In8_1_1");
    In9_1_1 = _get_double("In9_1_1");
    In17_1_1 = _get_double("In17_1_1");
    In17_1_2 = _get_double("In17_1_2");
    In17_1_3 = _get_double("In17_1_3");
    In17_1_4 = _get_double("In17_1_4");
    In17_1_5 = _get_double("In17_1_5");
    In17_1_6 = _get_double("In17_1_6");
    In17_1_7 = _get_double("In17_1_7");
    In17_1_8 = _get_double("In17_1_8");
    In17_1_9 = _get_double("In17_1_9");
    In20_1_1 = _get_int("In20_1_1");
    In21_1_1 = _get_double("In21_1_1");
    In21_1_2 = _get_double("In21_1_2");
    In21_1_3 = _get_double("In21_1_3");
    In21_1_4 = _get_double("In21_1_4");
    multiportswitch_vect_test_step(In5_1_1, In5_1_2, In5_1_3, In5_1_4, In5_1_5, In8_1_1, In9_1_1, In17_1_1, In17_1_2, In17_1_3, In17_1_4, In17_1_5, In17_1_6, In17_1_7, In17_1_8, In17_1_9, In20_1_1, In21_1_1, In21_1_2, In21_1_3, In21_1_4, &Out2_1_1, &Out3_2_1, &Out5_3_1, &Out6_4_1, &main_mem);
    _put_double("Out2_1_1", Out2_1_1);
    _put_double("Out3_2_1", Out3_2_1);
    _put_double("Out5_3_1", Out5_3_1);
    _put_double("Out6_4_1", Out6_4_1);
  }
  return 1;
}
