#include <assert.h>
#include "datatypeconversion_test.h"

/* C code generated by lustrec
   SVN version number 1.1-Unversioned directory
   Code is C99 compliant */
   
/* Import dependencies */
#include "conv.h"

/* Global constants (definitions) */

/* Struct definitions */
struct datatypeconversion_test_mem {struct _arrow_mem *ni_0; };


void datatypeconversion_test_reset (struct datatypeconversion_test_mem *self) {
  
  _arrow_reset(self->ni_0);
  return;
}

void datatypeconversion_test_step (double In1_1_1, double In2_1_1,
                                   double In3_1_1, double In4_1_1,
                                   double In5_1_1, double In6_1_1,
                                   double In7_1_1, double In8_1_1,
                                   double In9_1_1, double In11_1_1,
                                   double In12_1_1, double In13_1_1,
                                   double In14_1_1, double In15_1_1,
                                   double In16_1_1, double In17_1_1,
                                   double In18_1_1, double In19_1_1,
                                   double In20_1_1, double In21_1_1,
                                   double In23_1_1, double In24_1_1,
                                   int In25_1_1, int In26_1_1, int In27_1_1,
                                   int In28_1_1, int In29_1_1, int In30_1_1,
                                   int In31_1_1, int In32_1_1, int In33_1_1,
                                   int In35_1_1, int In36_1_1, 
                                   double (*Out1_1_1), double (*Out2_2_1),
                                   int (*Out3_3_1), int (*Out4_4_1),
                                   int (*Out5_5_1), int (*Out6_6_1),
                                   int (*Out7_7_1), int (*Out8_8_1),
                                   _Bool (*Out9_9_1), int (*Out11_10_1),
                                   int (*Out12_11_1), double (*Out13_12_1),
                                   double (*Out14_13_1), int (*Out15_14_1),
                                   int (*Out16_15_1), int (*Out17_16_1),
                                   int (*Out18_17_1), int (*Out19_18_1),
                                   int (*Out20_19_1), _Bool (*Out21_20_1),
                                   int (*Out23_21_1), int (*Out24_22_1),
                                   double (*Out25_23_1),
                                   double (*Out26_24_1), int (*Out27_25_1),
                                   int (*Out28_26_1), int (*Out29_27_1),
                                   int (*Out30_28_1), int (*Out31_29_1),
                                   int (*Out32_30_1), _Bool (*Out33_31_1),
                                   int (*Out35_32_1), int (*Out36_33_1),
                                   struct datatypeconversion_test_mem *self) {
  int DataTypeConversion10_1_1;
  int DataTypeConversion11_1_1;
  int DataTypeConversion14_1_1;
  int DataTypeConversion15_1_1;
  int DataTypeConversion16_1_1;
  int DataTypeConversion17_1_1;
  int DataTypeConversion18_1_1;
  int DataTypeConversion19_1_1;
  int DataTypeConversion20_1_1;
  int DataTypeConversion21_1_1;
  _Bool DataTypeConversion22_1_1;
  double DataTypeConversion24_1_1;
  double DataTypeConversion25_1_1;
  int DataTypeConversion2_1_1;
  _Bool DataTypeConversion34_1_1;
  int DataTypeConversion3_1_1;
  int DataTypeConversion4_1_1;
  int DataTypeConversion5_1_1;
  int DataTypeConversion6_1_1;
  int DataTypeConversion7_1_1;
  _Bool DataTypeConversion8_1_1;
  _Bool __datatypeconversion_test_1;
  double i_virtual_local;
  
  _arrow_step (1, 0, &__datatypeconversion_test_1, self->ni_0);
  if (__datatypeconversion_test_1) {
    i_virtual_local = 0.;
  } else {
    i_virtual_local = 1.;
  }
  if ((In9_1_1 == 0.)) {
    DataTypeConversion8_1_1 = 0;
  } else {
    DataTypeConversion8_1_1 = 1;
  }
  *Out9_9_1 = DataTypeConversion8_1_1;
  Zero_step (In8_1_1, &DataTypeConversion7_1_1);
  *Out8_8_1 = DataTypeConversion7_1_1;
  Zero_step (In7_1_1, &DataTypeConversion6_1_1);
  *Out7_7_1 = DataTypeConversion6_1_1;
  Zero_step (In6_1_1, &DataTypeConversion5_1_1);
  *Out6_6_1 = DataTypeConversion5_1_1;
  Zero_step (In5_1_1, &DataTypeConversion4_1_1);
  *Out5_5_1 = DataTypeConversion4_1_1;
  Zero_step (In4_1_1, &DataTypeConversion3_1_1);
  *Out4_4_1 = DataTypeConversion3_1_1;
  Zero_step (In3_1_1, &DataTypeConversion2_1_1);
  *Out3_3_1 = DataTypeConversion2_1_1;
  *Out36_33_1 = In36_1_1;
  *Out35_32_1 = In35_1_1;
  if ((In33_1_1 == 0)) {
    DataTypeConversion34_1_1 = 0;
  } else {
    DataTypeConversion34_1_1 = 1;
  }
  *Out33_31_1 = DataTypeConversion34_1_1;
  *Out32_30_1 = In32_1_1;
  *Out31_29_1 = In31_1_1;
  *Out30_28_1 = In30_1_1;
  *Out2_2_1 = In2_1_1;
  *Out29_27_1 = In29_1_1;
  *Out28_26_1 = In28_1_1;
  *Out27_25_1 = In27_1_1;
  DataTypeConversion25_1_1 = int_to_real(In26_1_1);
  *Out26_24_1 = DataTypeConversion25_1_1;
  DataTypeConversion24_1_1 = int_to_real(In25_1_1);
  *Out25_23_1 = DataTypeConversion24_1_1;
  Zero_step (In24_1_1, &DataTypeConversion15_1_1);
  *Out24_22_1 = DataTypeConversion15_1_1;
  Zero_step (In23_1_1, &DataTypeConversion14_1_1);
  *Out23_21_1 = DataTypeConversion14_1_1;
  if ((In21_1_1 == 0.)) {
    DataTypeConversion22_1_1 = 0;
  } else {
    DataTypeConversion22_1_1 = 1;
  }
  *Out21_20_1 = DataTypeConversion22_1_1;
  Zero_step (In20_1_1, &DataTypeConversion21_1_1);
  *Out20_19_1 = DataTypeConversion21_1_1;
  *Out1_1_1 = In1_1_1;
  Zero_step (In19_1_1, &DataTypeConversion20_1_1);
  *Out19_18_1 = DataTypeConversion20_1_1;
  Zero_step (In18_1_1, &DataTypeConversion19_1_1);
  *Out18_17_1 = DataTypeConversion19_1_1;
  Zero_step (In17_1_1, &DataTypeConversion18_1_1);
  *Out17_16_1 = DataTypeConversion18_1_1;
  Zero_step (In16_1_1, &DataTypeConversion17_1_1);
  *Out16_15_1 = DataTypeConversion17_1_1;
  Zero_step (In15_1_1, &DataTypeConversion16_1_1);
  *Out15_14_1 = DataTypeConversion16_1_1;
  *Out14_13_1 = In14_1_1;
  *Out13_12_1 = In13_1_1;
  Zero_step (In12_1_1, &DataTypeConversion11_1_1);
  *Out12_11_1 = DataTypeConversion11_1_1;
  Zero_step (In11_1_1, &DataTypeConversion10_1_1);
  *Out11_10_1 = DataTypeConversion10_1_1;
  return;
}

void Zero_step (double In, 
                int (*Out)
                ) {
  
  *Out = 0;
  return;
}

