/* C code generated by lustrec
   SVN version number 1.1-Unversioned directory
   Code is C99 compliant */
   
#ifndef _DATATYPECONVERSION_TEST
#define _DATATYPECONVERSION_TEST

/* Imports standard library */
#include "/usr/local/include/lustrec/arrow.h"


/* Import dependencies */
#include "conv.h"

/* Types definitions */

/* Global constant (declarations, definitions are in C file) */

/* Struct declarations */
struct datatypeconversion_test_mem;

/* Nodes declarations */
extern void datatypeconversion_test_reset (struct datatypeconversion_test_mem *self);

extern void datatypeconversion_test_step (double In1_1_1, double In2_1_1,
                                          double In3_1_1, double In4_1_1,
                                          double In5_1_1, double In6_1_1,
                                          double In7_1_1, double In8_1_1,
                                          double In9_1_1, double In11_1_1,
                                          double In12_1_1, double In13_1_1,
                                          double In14_1_1, double In15_1_1,
                                          double In16_1_1, double In17_1_1,
                                          double In18_1_1, double In19_1_1,
                                          double In20_1_1, double In21_1_1,
                                          double In23_1_1, double In24_1_1,
                                          int In25_1_1, int In26_1_1,
                                          int In27_1_1, int In28_1_1,
                                          int In29_1_1, int In30_1_1,
                                          int In31_1_1, int In32_1_1,
                                          int In33_1_1, int In35_1_1,
                                          int In36_1_1, 
                                          double (*Out1_1_1),
                                          double (*Out2_2_1),
                                          int (*Out3_3_1), int (*Out4_4_1),
                                          int (*Out5_5_1), int (*Out6_6_1),
                                          int (*Out7_7_1), int (*Out8_8_1),
                                          _Bool (*Out9_9_1),
                                          int (*Out11_10_1),
                                          int (*Out12_11_1),
                                          double (*Out13_12_1),
                                          double (*Out14_13_1),
                                          int (*Out15_14_1),
                                          int (*Out16_15_1),
                                          int (*Out17_16_1),
                                          int (*Out18_17_1),
                                          int (*Out19_18_1),
                                          int (*Out20_19_1),
                                          _Bool (*Out21_20_1),
                                          int (*Out23_21_1),
                                          int (*Out24_22_1),
                                          double (*Out25_23_1),
                                          double (*Out26_24_1),
                                          int (*Out27_25_1),
                                          int (*Out28_26_1),
                                          int (*Out29_27_1),
                                          int (*Out30_28_1),
                                          int (*Out31_29_1),
                                          int (*Out32_30_1),
                                          _Bool (*Out33_31_1),
                                          int (*Out35_32_1),
                                          int (*Out36_33_1),
                                          struct datatypeconversion_test_mem *self);

extern void Zero_step (double In, 
                       int (*Out)
                       );


#endif

