#include <stdio.h>
#include <unistd.h>
#include "/usr/local/include/lustrec/io_frontend.h"
#include <stdlib.h>
#include <assert.h>
#include "datatypeconversion_test_alloc.h"

/* C code generated by lustrec
   SVN version number 1.1-Unversioned directory
   Code is C99 compliant */
   
int main (int argc, char *argv[]) {
  /* Declaration of inputs/outputs variables */
  double In1_1_1 = 0.;
  double In2_1_1 = 0.;
  double In3_1_1 = 0.;
  double In4_1_1 = 0.;
  double In5_1_1 = 0.;
  double In6_1_1 = 0.;
  double In7_1_1 = 0.;
  double In8_1_1 = 0.;
  double In9_1_1 = 0.;
  double In11_1_1 = 0.;
  double In12_1_1 = 0.;
  double In13_1_1 = 0.;
  double In14_1_1 = 0.;
  double In15_1_1 = 0.;
  double In16_1_1 = 0.;
  double In17_1_1 = 0.;
  double In18_1_1 = 0.;
  double In19_1_1 = 0.;
  double In20_1_1 = 0.;
  double In21_1_1 = 0.;
  double In23_1_1 = 0.;
  double In24_1_1 = 0.;
  int In25_1_1 = 0;
  int In26_1_1 = 0;
  int In27_1_1 = 0;
  int In28_1_1 = 0;
  int In29_1_1 = 0;
  int In30_1_1 = 0;
  int In31_1_1 = 0;
  int In32_1_1 = 0;
  int In33_1_1 = 0;
  int In35_1_1 = 0;
  int In36_1_1 = 0;
  double Out1_1_1 = 0.;
  double Out2_2_1 = 0.;
  int Out3_3_1 = 0;
  int Out4_4_1 = 0;
  int Out5_5_1 = 0;
  int Out6_6_1 = 0;
  int Out7_7_1 = 0;
  int Out8_8_1 = 0;
  _Bool Out9_9_1 = 0;
  int Out11_10_1 = 0;
  int Out12_11_1 = 0;
  double Out13_12_1 = 0.;
  double Out14_13_1 = 0.;
  int Out15_14_1 = 0;
  int Out16_15_1 = 0;
  int Out17_16_1 = 0;
  int Out18_17_1 = 0;
  int Out19_18_1 = 0;
  int Out20_19_1 = 0;
  _Bool Out21_20_1 = 0;
  int Out23_21_1 = 0;
  int Out24_22_1 = 0;
  double Out25_23_1 = 0.;
  double Out26_24_1 = 0.;
  int Out27_25_1 = 0;
  int Out28_26_1 = 0;
  int Out29_27_1 = 0;
  int Out30_28_1 = 0;
  int Out31_29_1 = 0;
  int Out32_30_1 = 0;
  _Bool Out33_31_1 = 0;
  int Out35_32_1 = 0;
  int Out36_33_1 = 0;
  
  /* Main memory allocation */
  datatypeconversion_test_ALLOC(static,main_mem);
  
  /* Initialize the main memory */
  datatypeconversion_test_reset(&main_mem);
  
  ISATTY = isatty(0);
  
  /* Infinite loop */
  while(1){
    fflush(stdout);
    In1_1_1 = _get_double("In1_1_1");
    In2_1_1 = _get_double("In2_1_1");
    In3_1_1 = _get_double("In3_1_1");
    In4_1_1 = _get_double("In4_1_1");
    In5_1_1 = _get_double("In5_1_1");
    In6_1_1 = _get_double("In6_1_1");
    In7_1_1 = _get_double("In7_1_1");
    In8_1_1 = _get_double("In8_1_1");
    In9_1_1 = _get_double("In9_1_1");
    In11_1_1 = _get_double("In11_1_1");
    In12_1_1 = _get_double("In12_1_1");
    In13_1_1 = _get_double("In13_1_1");
    In14_1_1 = _get_double("In14_1_1");
    In15_1_1 = _get_double("In15_1_1");
    In16_1_1 = _get_double("In16_1_1");
    In17_1_1 = _get_double("In17_1_1");
    In18_1_1 = _get_double("In18_1_1");
    In19_1_1 = _get_double("In19_1_1");
    In20_1_1 = _get_double("In20_1_1");
    In21_1_1 = _get_double("In21_1_1");
    In23_1_1 = _get_double("In23_1_1");
    In24_1_1 = _get_double("In24_1_1");
    In25_1_1 = _get_int("In25_1_1");
    In26_1_1 = _get_int("In26_1_1");
    In27_1_1 = _get_int("In27_1_1");
    In28_1_1 = _get_int("In28_1_1");
    In29_1_1 = _get_int("In29_1_1");
    In30_1_1 = _get_int("In30_1_1");
    In31_1_1 = _get_int("In31_1_1");
    In32_1_1 = _get_int("In32_1_1");
    In33_1_1 = _get_int("In33_1_1");
    In35_1_1 = _get_int("In35_1_1");
    In36_1_1 = _get_int("In36_1_1");
    datatypeconversion_test_step(In1_1_1, In2_1_1, In3_1_1, In4_1_1, In5_1_1, In6_1_1, In7_1_1, In8_1_1, In9_1_1, In11_1_1, In12_1_1, In13_1_1, In14_1_1, In15_1_1, In16_1_1, In17_1_1, In18_1_1, In19_1_1, In20_1_1, In21_1_1, In23_1_1, In24_1_1, In25_1_1, In26_1_1, In27_1_1, In28_1_1, In29_1_1, In30_1_1, In31_1_1, In32_1_1, In33_1_1, In35_1_1, In36_1_1, &Out1_1_1, &Out2_2_1, &Out3_3_1, &Out4_4_1, &Out5_5_1, &Out6_6_1, &Out7_7_1, &Out8_8_1, &Out9_9_1, &Out11_10_1, &Out12_11_1, &Out13_12_1, &Out14_13_1, &Out15_14_1, &Out16_15_1, &Out17_16_1, &Out18_17_1, &Out19_18_1, &Out20_19_1, &Out21_20_1, &Out23_21_1, &Out24_22_1, &Out25_23_1, &Out26_24_1, &Out27_25_1, &Out28_26_1, &Out29_27_1, &Out30_28_1, &Out31_29_1, &Out32_30_1, &Out33_31_1, &Out35_32_1, &Out36_33_1, &main_mem);
    _put_double("Out1_1_1", Out1_1_1);
    _put_double("Out2_2_1", Out2_2_1);
    _put_int("Out3_3_1", Out3_3_1);
    _put_int("Out4_4_1", Out4_4_1);
    _put_int("Out5_5_1", Out5_5_1);
    _put_int("Out6_6_1", Out6_6_1);
    _put_int("Out7_7_1", Out7_7_1);
    _put_int("Out8_8_1", Out8_8_1);
    _put_bool("Out9_9_1", Out9_9_1);
    _put_int("Out11_10_1", Out11_10_1);
    _put_int("Out12_11_1", Out12_11_1);
    _put_double("Out13_12_1", Out13_12_1);
    _put_double("Out14_13_1", Out14_13_1);
    _put_int("Out15_14_1", Out15_14_1);
    _put_int("Out16_15_1", Out16_15_1);
    _put_int("Out17_16_1", Out17_16_1);
    _put_int("Out18_17_1", Out18_17_1);
    _put_int("Out19_18_1", Out19_18_1);
    _put_int("Out20_19_1", Out20_19_1);
    _put_bool("Out21_20_1", Out21_20_1);
    _put_int("Out23_21_1", Out23_21_1);
    _put_int("Out24_22_1", Out24_22_1);
    _put_double("Out25_23_1", Out25_23_1);
    _put_double("Out26_24_1", Out26_24_1);
    _put_int("Out27_25_1", Out27_25_1);
    _put_int("Out28_26_1", Out28_26_1);
    _put_int("Out29_27_1", Out29_27_1);
    _put_int("Out30_28_1", Out30_28_1);
    _put_int("Out31_29_1", Out31_29_1);
    _put_int("Out32_30_1", Out32_30_1);
    _put_bool("Out33_31_1", Out33_31_1);
    _put_int("Out35_32_1", Out35_32_1);
    _put_int("Out36_33_1", Out36_33_1);
  }
  return 1;
}
